//! Static knowledge: format names → descriptions/URLs/extensions/MIME, codec IDs → descriptions.

use crate::model::StreamKind;

#[derive(Debug, Clone, Copy, Default)]
pub struct FormatInfo {
    pub info: &'static str,
    pub url: &'static str,
    pub extensions: &'static str,
    pub commercial: &'static str,
    pub mime: &'static str,
}

macro_rules! fi {
    ($info:expr, $url:expr, $ext:expr, $com:expr, $mime:expr) => {
        FormatInfo { info: $info, url: $url, extensions: $ext, commercial: $com, mime: $mime }
    };
}

/// Container (General stream) formats.
static GENERAL: &[(&str, FormatInfo)] = &[
    ("Matroska", fi!("", "https://matroska.org/downloads/windows.html", "mkv mk3d mka mks", "Matroska", "")),
    ("WebM", fi!("", "http://www.webmproject.org/", "webm", "WebM", "video/webm")),
    ("MPEG-4", fi!("", "", "braw mov mp4 m4v m4a m4b m4p m4r 3ga 3gpa 3gpp 3gp 3gpp2 3g2 k3g jpm jpx mqv ismv isma ismt f4a f4b f4v", "MPEG-4", "video/mp4")),
    ("QuickTime", fi!("", "", "mov qt", "QuickTime", "video/quicktime")),
    ("AVI", fi!("Audio Video Interleave", "", "avi", "AVI", "video/vnd.avi")),
    ("Wave", fi!("", "", "act at9 wav", "Wave", "audio/vnd.wave")),
    ("AIFF", fi!("Apple/SGI", "", "aiff aifc aif", "AIFF", "audio/x-aiff")),
    ("AU", fi!("uLaw/AU Audio File", "", "au", "AU", "audio/basic")),
    ("CAF", fi!("Core Audio Format", "https://developer.apple.com/library/content/documentation/MusicAudio/Reference/CAFSpec/CAF_overview/CAF_overview.html", "caf", "CAF", "audio/x-caf")),
    ("Ogg", fi!("", "https://en.wikipedia.org/wiki/Ogg", "oga ogg ogm ogv ogx opus spx", "Ogg", "video/ogg")),
    ("Windows Media", fi!("", "", "asf dvr-ms wma wmv", "Windows Media", "video/x-ms-wmv")),
    ("MPEG-PS", fi!("", "", "mpeg mpg m2p vob vro pss evo", "MPEG-PS", "video/MP2P")),
    ("MPEG-TS", fi!("", "", "ts m2t m2s m4t m4s tmf ts tp trp ty", "MPEG-TS", "video/MP2T")),
    ("BDAV", fi!("Blu-ray Video", "", "m2ts mts ssif", "BDAV", "")),
    ("Flash Video", fi!("", "http://www.macromedia.com/go/getflashplayer", "flv", "Flash Video", "video/x-flv")),
    ("RealMedia", fi!("", "", "rm rmvb ra", "RealMedia", "application/vnd.rn-realmedia")),
    ("MXF", fi!("", "", "mxf", "MXF", "application/mxf")),
    ("Nut", fi!("", "", "", "Nut", "")),
    ("IVF", fi!("", "", "ivf", "IVF", "")),
    ("DV", fi!("", "", "dv dif", "DV", "video/DV")),
    ("AVC", fi!("Advanced Video Codec", "http://developers.videolan.org/x264.html", "avc h264 264", "AVC", "video/H264")),
    ("HEVC", fi!("High Efficiency Video Coding", "http://www.itu.int", "hevc h265 265", "HEVC", "video/H265")),
    ("MPEG Video", fi!("", "", "mpgv mpv mp1v m1v mp2v m2v", "MPEG Video", "video/MPV")),
    ("MPEG-4 Visual", fi!("", "", "m4v mp4v", "MPEG-4 Visual", "video/MP4V-ES")),
    ("AV1", fi!("AOMedia Video 1", "http://aomedia.org/", "obu av1", "AV1", "")),
    ("VC-3", fi!("", "", "", "VC-3", "")),
    ("JPEG", fi!("", "", "h3d jpeg jpg jpe jps mpo", "JPEG", "image/jpeg")),
    ("JPEG 2000", fi!("", "http://www.morgan-multimedia.com/JPEG 2000/", "jp2", "JPEG 2000", "image/jp2")),
    ("PNG", fi!("Portable Network Graphic", "", "png pns", "PNG", "image/png")),
    ("GIF", fi!("Graphics Interchange Format", "", "gif gis", "GIF", "image/gif")),
    ("Bitmap", fi!("", "", "bmp bms", "Bitmap", "image/bmp")),
    ("TIFF", fi!("", "", "tiff tif", "TIFF", "image/tiff")),
    ("WebP", fi!("", "", "webp", "WebP", "image/webp")),
    ("MPEG Audio", fi!("", "", "m1a mpa mpa1 mp1 m2a mpa2 mp2 mp3", "MPEG Audio", "audio/mpeg")),
    ("ADTS", fi!("Audio Data Transport Stream", "", "aac aacp adts", "ADTS", "")),
    ("LATM", fi!("", "", "", "LATM", "")),
    ("AC-3", fi!("Audio Coding 3", "https://en.wikipedia.org/wiki/AC3", "ac3", "Dolby Digital", "")),
    ("E-AC-3", fi!("Enhanced AC-3", "https://en.wikipedia.org/wiki/Dolby_Digital_Plus", "dd+ ec3 eac3", "Dolby Digital Plus", "audio/eac3")),
    ("DTS", fi!("Digital Theater Systems", "https://en.wikipedia.org/wiki/DTS_(sound_system)", "dts dtshd", "DTS", "")),
    ("MLP", fi!("Meridian Lossless Packing", "", "mlp", "MLP Lossless", "")),
    ("MLP FBA", fi!("Meridian Lossless Packing FBA", "", "thd", "Dolby TrueHD", "")),
    ("FLAC", fi!("Free Lossless Audio Codec", "https://xiph.org/flac/", "fla flac", "FLAC", "audio/x-flac")),
    ("WavPack", fi!("", "http://www.wavpack.com", "wv wvc", "WavPack", "")),
    ("TTA", fi!("", "", "tta", "TTA", "")),
    ("Monkey's Audio", fi!("", "http://www.monkeysaudio.com", "ape mac", "Monkey's Audio", "")),
    ("AMR", fi!("Adaptive Multi-Rate", "http://www.apple.com/quicktime/download/standalone.html", "amr", "AMR", "audio/AMR")),
    ("SubRip", fi!("", "http://ffdshow.sourceforge.net/tikiwiki/tiki-index.php?page=Getting+ffdshow", "srt", "SubRip", "")),
    ("ASS", fi!("Advanced SubStation Alpha", "http://ffdshow.sourceforge.net/tikiwiki/tiki-index.php?page=Getting+ffdshow", "ssa", "ASS", "")),
    ("SSA", fi!("SubStation Alpha", "http://ffdshow.sourceforge.net/tikiwiki/tiki-index.php?page=Getting+ffdshow", "ssa", "SSA", "")),
    ("WebVTT", fi!("", "", "vtt", "WebVTT", "")),
    ("VobSub", fi!("", "", "idx sub", "VobSub", "")),
];

/// Elementary stream formats (any non-General kind); General falls back here too.
static STREAM: &[(&str, FormatInfo)] = &[
    ("AVC", fi!("Advanced Video Codec", "http://developers.videolan.org/x264.html", "", "AVC", "video/H264")),
    ("HEVC", fi!("High Efficiency Video Coding", "http://www.itu.int", "", "HEVC", "video/H265")),
    ("MPEG Video", fi!("", "", "", "MPEG Video", "video/MPV")),
    ("MPEG-4 Visual", fi!("", "", "", "MPEG-4 Visual", "video/MP4V-ES")),
    ("AV1", fi!("AOMedia Video 1", "http://aomedia.org/", "", "AV1", "")),
    ("VP8", fi!("", "http://www.webmproject.org/", "", "VP8", "")),
    ("VP9", fi!("", "", "", "VP9", "")),
    ("Theora", fi!("", "http://www.theora.org/", "", "Theora", "")),
    ("JPEG", fi!("", "", "", "JPEG", "video/JPEG")),
    ("H.263", fi!("", "", "", "H.263", "video/H263")),
    ("Sorenson Spark", fi!("", "", "", "Sorenson Spark", "")),
    ("RealVideo 1", fi!("", "", "", "RealVideo 1", "")),
    ("RealVideo 2", fi!("", "", "", "RealVideo 2", "")),
    ("RealVideo 3", fi!("", "", "", "RealVideo 3", "")),
    ("RealVideo 4", fi!("", "", "", "RealVideo 4", "")),
    ("VC-1", fi!("", "", "", "VC-1", "")),
    ("VC-3", fi!("", "", "", "VC-3", "")),
    ("WMV1", fi!("", "", "", "WMV1", "")),
    ("WMV2", fi!("", "", "", "WMV2", "")),
    ("WMV3", fi!("", "", "", "WMV3", "")),
    ("DV", fi!("", "", "", "DV", "video/DV")),
    ("YUV", fi!("", "", "", "YUV", "")),
    ("RGB", fi!("", "", "", "RGB", "")),
    ("ProRes", fi!("", "", "", "ProRes", "")),
    ("PNG", fi!("Portable Network Graphic", "", "", "PNG", "image/png")),
    ("GIF", fi!("Graphics Interchange Format", "", "", "GIF", "image/gif")),
    ("Bitmap", fi!("", "", "", "Bitmap", "image/bmp")),
    ("TIFF", fi!("", "", "", "TIFF", "image/tiff")),
    ("WebP", fi!("", "", "", "WebP", "image/webp")),
    ("JPEG 2000", fi!("", "http://www.morgan-multimedia.com/JPEG 2000/", "", "JPEG 2000", "image/jp2")),
    ("AAC", fi!("Advanced Audio Codec", "", "", "AAC", "")),
    ("MPEG Audio", fi!("", "", "", "MPEG Audio", "audio/mpeg")),
    ("AC-3", fi!("Audio Coding 3", "https://en.wikipedia.org/wiki/AC3", "", "Dolby Digital", "")),
    ("E-AC-3", fi!("Enhanced AC-3", "https://en.wikipedia.org/wiki/Dolby_Digital_Plus", "", "Dolby Digital Plus", "audio/eac3")),
    ("DTS", fi!("Digital Theater Systems", "https://en.wikipedia.org/wiki/DTS_(sound_system)", "", "DTS", "")),
    ("MLP", fi!("Meridian Lossless Packing", "", "", "MLP Lossless", "")),
    ("MLP FBA", fi!("Meridian Lossless Packing FBA", "", "", "Dolby TrueHD", "")),
    ("FLAC", fi!("Free Lossless Audio Codec", "https://xiph.org/flac/", "", "FLAC", "audio/x-flac")),
    ("Vorbis", fi!("", "http://www.vorbis.com/", "", "Vorbis", "audio/vorbis")),
    ("Opus", fi!("", "http://opus-codec.org/", "", "Opus", "audio/opus")),
    ("Speex", fi!("", "http://www.speex.org/", "", "Speex", "audio/speex")),
    ("PCM", fi!("", "", "", "PCM", "")),
    ("ADPCM", fi!("", "", "", "ADPCM", "")),
    ("ALAC", fi!("", "", "", "ALAC", "")),
    ("WMA", fi!("", "", "", "WMA", "")),
    ("WavPack", fi!("", "http://www.wavpack.com", "", "WavPack", "")),
    ("TTA", fi!("", "", "", "TTA", "")),
    ("Monkey's Audio", fi!("", "http://www.monkeysaudio.com", "", "Monkey's Audio", "")),
    ("AMR", fi!("Adaptive Multi-Rate", "http://www.apple.com/quicktime/download/standalone.html", "", "AMR", "audio/AMR")),
    ("Cook", fi!("", "", "", "Cook", "")),
    ("UTF-8", fi!("", "", "", "UTF-8", "")),
    ("ASS", fi!("Advanced SubStation Alpha", "", "", "ASS", "")),
    ("SSA", fi!("SubStation Alpha", "", "", "SSA", "")),
    ("WebVTT", fi!("", "", "", "WebVTT", "")),
    ("VobSub", fi!("", "", "", "VobSub", "")),
    ("PGS", fi!("", "", "", "PGS", "")),
    ("Timed Text", fi!("", "", "", "Timed Text", "")),
    ("RLE", fi!("Run-length encoding", "", "", "RLE", "")),
    ("SubRip", fi!("", "", "", "SubRip", "")),
    ("Timecode", fi!("", "", "", "Timecode", "")),
];

pub fn format_info(kind: StreamKind, format: &str) -> Option<FormatInfo> {
    let find = |t: &[(&str, FormatInfo)]| t.iter().find(|(n, _)| *n == format).map(|(_, i)| *i);
    if kind == StreamKind::General {
        find(GENERAL).or_else(|| find(STREAM))
    } else {
        find(STREAM).or_else(|| find(GENERAL))
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct CodecIdInfo {
    pub info: &'static str,
    pub hint: &'static str,
    pub url: &'static str,
    pub description: &'static str,
}

macro_rules! ci {
    ($info:expr, $hint:expr, $url:expr, $desc:expr) => {
        CodecIdInfo { info: $info, hint: $hint, url: $url, description: $desc }
    };
}

const FFDSHOW: &str = "http://ffdshow-tryout.sourceforge.net/";
const MS: &str = "http://www.microsoft.com/windows/";
const MSWM: &str = "http://www.microsoft.com/windows/windowsmedia/format/codecdownload.aspx";
const QT: &str = "http://www.apple.com/quicktime/download/standalone.html";
const FHG: &str = "http://www.iis.fraunhofer.de/amm/index.html";

static CODEC_IDS: &[(&str, CodecIdInfo)] = &[
    // Matroska
    ("V_MPEG4/ISO/AVC", ci!("", "", FFDSHOW, "")),
    ("V_MPEGH/ISO/HEVC", ci!("", "", "", "")),
    ("V_MPEG4/ISO/ASP", ci!("Advanced Simple Profile", "", "http://www.xvid.org/Downloads.15.0.html", "")),
    ("V_MPEG4/ISO/SP", ci!("Simple Profile", "", "http://www.xvid.org/Downloads.15.0.html", "")),
    ("V_MPEG4/ISO/AP", ci!("Advanced Profile", "", "http://www.xvid.org/Downloads.15.0.html", "")),
    ("V_MPEG4/MS/V3", ci!("Microsoft MPEG-4 v3 (pre-standard)", "", "", "")),
    ("V_MPEG2", ci!("MPEG 1 or 2 Video", "", FFDSHOW, "")),
    ("V_MPEG1", ci!("MPEG 1 or 2 Video", "", FFDSHOW, "")),
    ("V_VP8", ci!("", "", "http://www.webmproject.org/", "")),
    ("V_VP9", ci!("", "", "http://www.webmproject.org/", "")),
    ("V_AV1", ci!("", "", "http://aomedia.org/", "")),
    ("V_THEORA", ci!("", "", "http://www.theora.org/", "")),
    ("V_MS/VFW/FOURCC", ci!("", "", "", "")),
    ("V_REAL/RV40", ci!("", "", "http://www.real.com", "")),
    ("V_QUICKTIME", ci!("", "", QT, "")),
    ("A_AAC", ci!("", "", "", "")),
    ("A_AAC-2", ci!("", "", "", "")),
    ("A_AAC/MPEG4/LC", ci!("", "", "", "")),
    ("A_AAC/MPEG4/LC/SBR", ci!("", "", "", "")),
    ("A_AAC/MPEG2/LC", ci!("", "", "", "")),
    ("A_AC3", ci!("", "", "", "")),
    ("A_EAC3", ci!("", "", "", "")),
    ("A_TRUEHD", ci!("", "", "", "")),
    ("A_MLP", ci!("", "", "", "")),
    ("A_DTS", ci!("", "", "", "")),
    ("A_FLAC", ci!("", "", "https://xiph.org/flac", "")),
    ("A_MPEG/L3", ci!("", "MP3", FHG, "")),
    ("A_MPEG/L2", ci!("", "MP2", "", "")),
    ("A_MPEG/L1", ci!("", "MP1", "", "")),
    ("A_OPUS", ci!("", "", "http://opus-codec.org", "")),
    ("A_VORBIS", ci!("", "", "http://www.vorbis.com", "")),
    ("A_PCM/INT/LIT", ci!("", "", "", "")),
    ("A_PCM/INT/BIG", ci!("", "", "", "")),
    ("A_PCM/FLOAT/IEEE", ci!("", "", "", "")),
    ("A_ALAC", ci!("", "", "", "")),
    ("A_WAVPACK4", ci!("", "", "http://www.wavpack.com", "")),
    ("A_TTA1", ci!("", "", "", "")),
    ("A_MS/ACM", ci!("", "", "", "")),
    ("A_REAL/COOK", ci!("", "", "http://www.real.com", "")),
    ("S_TEXT/UTF8", ci!("UTF-8 Plain Text", "", "", "")),
    ("S_TEXT/ASCII", ci!("ASCII Plain Text", "", "", "")),
    ("S_TEXT/ASS", ci!("Advanced Sub Station Alpha", "", "", "")),
    ("S_TEXT/SSA", ci!("Sub Station Alpha", "", "", "")),
    ("S_TEXT/USF", ci!("Universal Subtitle Format", "", "", "")),
    ("S_TEXT/WEBVTT", ci!("Web Video Text Tracks", "", "", "")),
    ("S_VOBSUB", ci!("Picture based", "", "", "")),
    ("S_HDMV/PGS", ci!("Picture based", "", "", "")),
    ("S_HDMV/TEXTST", ci!("", "", "", "")),
    ("S_DVBSUB", ci!("", "", "", "")),
    ("S_KATE", ci!("", "", "", "")),
    // MP4
    ("avc1", ci!("Advanced Video Coding", "", "", "")),
    ("avc3", ci!("Advanced Video Coding", "", "", "")),
    ("hvc1", ci!("High Efficiency Video Coding", "", "http://www.itu.int/", "")),
    ("hev1", ci!("High Efficiency Video Coding", "", "http://www.itu.int/", "")),
    ("av01", ci!("", "", "http://aomedia.org/", "")),
    ("vp09", ci!("", "", "http://www.webmproject.org/", "")),
    ("vp08", ci!("", "", "http://www.webmproject.org/", "")),
    ("mp4v-20", ci!("", "", "", "")),
    ("s263", ci!("", "", QT, "")),
    ("mjpa", ci!("Motion JPEG A", "", QT, "")),
    ("jpeg", ci!("", "", QT, "")),
    ("apch", ci!("Apple ProRes 422 High Quality", "", "", "")),
    ("apcn", ci!("Apple ProRes 422 Standard Definition", "", "", "")),
    ("apcs", ci!("Apple ProRes 422 LT", "", "", "")),
    ("apco", ci!("Apple ProRes 422 Proxy", "", "", "")),
    ("ap4h", ci!("Apple ProRes 4444", "", "", "")),
    ("mp4a-40-2", ci!("", "", "", "")),
    ("mp4a-40-5", ci!("", "", "", "")),
    ("mp4a-40-29", ci!("", "", "", "")),
    ("mp4a-6B", ci!("", "", "", "")),
    ("mp4a-69", ci!("", "", "", "")),
    ("alac", ci!("Apple Lossless Audio Codec", "", QT, "")),
    ("ac-3", ci!("", "", "", "")),
    ("ec-3", ci!("", "", "", "")),
    ("dtsc", ci!("", "", "", "")),
    ("Opus", ci!("", "", "http://opus-codec.org", "")),
    ("fLaC", ci!("", "", "https://xiph.org/flac", "")),
    ("sowt", ci!("", "", QT, "")),
    ("twos", ci!("", "", QT, "")),
    ("lpcm", ci!("", "", "", "")),
    ("in24", ci!("", "", QT, "")),
    ("in32", ci!("", "", QT, "")),
    ("fl32", ci!("", "", QT, "")),
    ("fl64", ci!("", "", QT, "")),
    ("samr", ci!("", "", QT, "")),
    ("tx3g", ci!("", "", "", "")),
    ("text", ci!("", "", "", "")),
    // AVI / WAV
    ("1", ci!("", "", MS, "")),
    ("3", ci!("", "", "", "")),
    ("55", ci!("", "MP3", FHG, "")),
    ("50", ci!("", "MP2", "", "")),
    ("2000", ci!("", "", "", "")),
    ("2001", ci!("", "", "", "")),
    ("161", ci!("Windows Media Audio", "", MSWM, "Windows Media Audio V8")),
    ("160", ci!("Windows Media Audio", "", MSWM, "Windows Media Audio V7")),
    ("162", ci!("Windows Media Audio Professional", "", MSWM, "")),
    ("163", ci!("Windows Media Audio Lossless", "", MSWM, "")),
    ("FF", ci!("", "", "", "")),
    ("00000001-0000-0010-8000-00AA00389B71", ci!("", "", MS, "")),
    ("00000003-0000-0010-8000-00AA00389B71", ci!("", "IEEE ", MS, "")),
    ("FMP4", ci!("", "", FFDSHOW, "")),
    ("XVID", ci!("", "", "http://www.xvid.org/Downloads.15.0.html", "")),
    ("xvid", ci!("", "", "http://www.xvid.org/Downloads.15.0.html", "")),
    ("DIVX", ci!("", "", "http://www.divx.com/divx/", "")),
    ("DX50", ci!("", "", "http://www.divx.com/divx/", "")),
    ("MP43", ci!("Microsoft MPEG-4 v3 (pre-standard)", "Microsoft", "", "msmpeg4v3")),
    ("MP42", ci!("Microsoft MPEG-4 v2 (pre-standard)", "Microsoft", "", "msmpeg4v2")),
    ("H264", ci!("", "", "", "")),
    ("h264", ci!("", "", "", "")),
    ("X264", ci!("", "", "http://developers.videolan.org/x264.html", "")),
    ("x264", ci!("", "", "http://developers.videolan.org/x264.html", "")),
    ("MJPG", ci!("", "", "", "")),
    ("I420", ci!("8 bit Y plane followed by 8 bit 2x2 subsampled U and V planes.", "", "", "")),
    ("WMV1", ci!("Windows Media Video 7", "", MSWM, "wmv1")),
    ("WMV2", ci!("Windows Media Video 8", "", MSWM, "wmv2")),
    ("WMV3", ci!("Windows Media Video 9", "", MSWM, "wmv3")),
    ("WVC1", ci!("Windows Media Video 9 Advanced Profile", "", MSWM, "")),
    ("dvsd", ci!("", "", "", "")),
    ("DVSD", ci!("", "", "", "")),
    // RealMedia
    ("RV10", ci!("Based on H.263, Real Player 5", "", "http://www.real.com", "")),
    ("RV20", ci!("Based on H.263, Real Player 6", "", "http://www.real.com", "")),
    ("RV30", ci!("Based on H.264, Real Player 8", "", "http://www.real.com", "")),
    ("RV40", ci!("Based on H.264, Real Player 9", "", "http://www.real.com", "")),
    ("dnet", ci!("Real Player 3", "", "http://www.real.com", "")),
    ("cook", ci!("Based on G.722.1, Real Player 6", "", "http://www.real.com", "")),
    // MPEG-TS stream types
    ("27", ci!("", "", "", "")),
    ("36", ci!("", "", "", "")),
    ("2", ci!("", "", "", "")),
    ("15", ci!("", "", "", "")),
    ("17", ci!("", "", "", "")),
    ("129", ci!("", "", "", "")),
    ("135", ci!("", "", "", "")),
    ("130", ci!("", "", "", "")),
    ("131", ci!("", "", "", "")),
    ("134", ci!("", "", "", "")),
    ("128", ci!("", "", "", "")),
    ("3gp4", ci!("", "", "http://www.3gpp.org/", "")),
    ("3gp5", ci!("", "", "http://www.3gpp.org/", "")),
    ("3gp6", ci!("", "", "http://www.3gpp.org/", "")),
    ("M4A ", ci!("", "", "http://www.apple.com/itunes/", "")),
    ("isom", ci!("", "", QT, "")),
    ("mp41", ci!("", "", QT, "")),
    ("mp42", ci!("", "", QT, "")),
    ("qt  ", ci!("", "", QT, "")),
];

pub fn codec_id_info(codec_id: &str) -> Option<CodecIdInfo> {
    CODEC_IDS.iter().find(|(n, _)| *n == codec_id).map(|(_, i)| *i)
}
