// Display labels for the English text report. Observed from the reference output (tests/oracle/_labels.tsv)
// with the standard MediaInfo English names for the rest.

use std::collections::HashMap;
use std::sync::OnceLock;

static LABELS: &[(&str, &str)] = &[
    ("00:00:00.000", "00:00:00.000"),
    ("00:00:00.500", "00:00:00.500"),
    ("Accompaniment", "Accompaniment"),
    ("ActiveFormatDescription/String", "Active Format Description"),
    ("Actor", "Actor"),
    ("Actor_Character", "Character"),
    ("Added_Date", "Added date"),
    ("Album", "Album"),
    ("Album/Performer", "Album performer"),
    ("Album/Performer/Sort", "Album performer sort"),
    ("Album/Performer/Url", "Album performer URL"),
    ("Album/Sort", "Album sort"),
    ("Album_More", "Album, more info"),
    ("Album_ReplayGain_Gain/String", "Album replay gain"),
    ("Album_ReplayGain_Peak", "Album replay gain peak"),
    ("Alignment", "Alignment"),
    ("Alignment/String", "Alignment"),
    ("AlternateGroup", "Alternate group"),
    ("AlternateGroup/String", "Alternate group"),
    ("Archival_Location", "Archival location"),
    ("Arranger", "Arranger"),
    ("ArtDirector", "Art director"),
    ("AssistantDirector", "Assistant director"),
    ("AudioCount", "Count of audio streams"),
    ("Audio_Codec_List", "Audio codecs"),
    ("Audio_Format_List", "Audio_Format_List"),
    ("Audio_Format_WithHint_List", "Audio_Format_WithHint_List"),
    ("Audio_Language_List", "Audio_Language_List"),
    ("BPM", "BPM"),
    ("BarCode", "Bar code"),
    ("BitDepth", "Bit depth"),
    ("BitDepth/String", "Bit depth"),
    ("BitDepth_Detected/String", "Bit depth detected"),
    ("BitDepth_Stored/String", "Bit depth stored"),
    ("BitRate", "Bit rate"),
    ("BitRate/String", "Bit rate"),
    ("BitRate_Encoded/String", "Encoded bit rate"),
    ("BitRate_Maximum", "Maximum bit rate"),
    ("BitRate_Maximum/String", "Maximum bit rate"),
    ("BitRate_Minimum", "Minimum bit rate"),
    ("BitRate_Minimum/String", "Minimum bit rate"),
    ("BitRate_Mode", "Bit rate mode"),
    ("BitRate_Mode/String", "Bit rate mode"),
    ("BitRate_Nominal", "Nominal bit rate"),
    ("BitRate_Nominal/String", "Nominal bit rate"),
    ("Bits-(Pixel*Frame)", "Bits/(Pixel*Frame)"),
    ("BlockAlignment", "BlockAlignment"),
    ("BufferSize", "Buffer size"),
    ("CatalogNumber", "Catalog number"),
    ("Channel(s)", "Channel(s)"),
    ("Channel(s)/String", "Channel(s)"),
    ("Channel(s)_Original", "Channel(s)_Original"),
    ("Channel(s)_Original/String", "Channel(s)_Original"),
    ("ChannelLayout", "Channel layout"),
    ("ChannelLayout_Original", "ChannelLayout_Original"),
    ("ChannelPositions", "Channel positions"),
    ("ChannelPositions/String2", "Channel positions"),
    ("ChannelPositions_Original", "ChannelPositions_Original"),
    ("Chapter", "Chapter"),
    ("Chapters_Pos_Begin", "Chapters_Pos_Begin"),
    ("Chapters_Pos_End", "Chapters_Pos_End"),
    ("Choreographer", "Choreographer"),
    ("ChromaSubsampling", "Chroma subsampling"),
    ("ChromaSubsampling/String", "Chroma subsampling"),
    ("ChromaSubsampling_Position", "Chroma subsampling position"),
    ("CoDirector", "Co-director"),
    ("CoProducer", "Co-producer"),
    ("Codec", "Codec"),
    ("Codec/CC", "Codec/CC"),
    ("Codec/Extensions", "Codec extensions"),
    ("Codec/Family", "Codec family"),
    ("Codec/Info", "Codec/Info"),
    ("Codec/String", "Codec"),
    ("Codec/Url", "Codec URL"),
    ("CodecConfigurationBox", "Codec configuration box"),
    ("CodecID", "Codec ID"),
    ("CodecID/Hint", "Codec ID/Hint"),
    ("CodecID/Info", "Codec ID/Info"),
    ("CodecID/String", "Codec ID"),
    ("CodecID/Url", "Codec ID/Url"),
    ("CodecID_Compatible", "CodecID_Compatible"),
    ("CodecID_Description", "Description of the codec"),
    ("CodecID_Version", "CodecID_Version"),
    ("Codec_Description", "Codec description"),
    ("Codec_Profile", "Codec profile"),
    ("Codec_Settings", "Codec settings"),
    ("Codec_Settings_Automatic", "Codec settings, automatic"),
    ("Collection", "Collection"),
    ("ColorSpace", "Color space"),
    ("Colorimetry", "Colorimetry"),
    ("Comic", "Comic"),
    ("Comic/Position_Total", "Comic position total"),
    ("Comic_More", "Comic, more info"),
    ("Comment", "Comment"),
    ("CommissionedBy", "Commissioned by"),
    ("Compilation/String", "Compilation"),
    ("CompleteName", "Complete name"),
    ("CompleteName_Last", "Complete name (last)"),
    ("Composer", "Composer"),
    ("Composer/Nationality", "Composer nationality"),
    ("Composer/Sort", "Composer sort"),
    ("Compression_Mode", "Compression mode"),
    ("Compression_Mode/String", "Compression mode"),
    ("Compression_Ratio", "Compression ratio"),
    ("Conductor", "Conductor"),
    ("ContentType", "Content type"),
    ("Copyright", "Copyright"),
    ("Copyright/Url", "Copyright URL"),
    ("CostumeDesigner", "Costume designer"),
    ("Count", "Count"),
    ("Country", "Country"),
    ("Cover", "Cover"),
    ("Cover_Data", "Cover data"),
    ("Cover_Description", "Cover description"),
    ("Cover_Mime", "Cover MIME"),
    ("Cover_Type", "Cover type"),
    ("Cropped", "Cropped"),
    ("DataSize", "DataSize"),
    ("Default", "Default"),
    ("Default/String", "Default"),
    ("Delay", "Delay"),
    ("Delay/String", "Delay"),
    ("Delay/String1", "Delay"),
    ("Delay/String2", "Delay"),
    ("Delay/String3", "Delay"),
    ("Delay_DropFrame", "Delay_DropFrame"),
    ("Delay_Original", "Delay_Original"),
    ("Delay_Original/String", "Delay_Original"),
    ("Delay_Original/String3", "Delay_Original"),
    ("Delay_Original_DropFrame", "Delay_Original_DropFrame"),
    ("Delay_Original_Settings", "Delay_Original_Settings"),
    ("Delay_Original_Source", "Delay_Original_Source"),
    ("Delay_SDTI", "Delay_SDTI"),
    ("Delay_Settings", "Delay_Settings"),
    ("Delay_Source", "Delay, origin"),
    ("Delay_Source/String", "Delay, origin"),
    ("Density/String", "Density"),
    ("Density_Unit", "Density_Unit"),
    ("Density_X", "Density_X"),
    ("Density_Y", "Density_Y"),
    ("Description", "Description"),
    ("Dimensions", "Dimensions"),
    ("Director", "Director"),
    ("DirectorOfPhotography", "Director of photography"),
    ("Disabled", "Disabled"),
    ("Disabled/String", "Disabled"),
    ("DisplayAspectRatio", "Display aspect ratio"),
    ("DisplayAspectRatio/String", "Display aspect ratio"),
    ("DisplayAspectRatio_CleanAperture/String", "Clean aperture display aspect ratio"),
    ("DisplayAspectRatio_Original/String", "Original display aspect ratio"),
    ("DistributedBy", "Distributed by"),
    ("Domain", "Domain"),
    ("DotsPerInch", "Dots per inch"),
    ("Duration", "Duration"),
    ("Duration/String", "Duration"),
    ("Duration/String1", "Duration"),
    ("Duration/String2", "Duration"),
    ("Duration/String3", "Duration"),
    ("Duration/String4", "Duration"),
    ("Duration/String5", "Duration"),
    ("Duration_End", "Duration end"),
    ("Duration_FirstFrame/String", "Duration_FirstFrame"),
    ("Duration_LastFrame", "Duration_LastFrame"),
    ("Duration_LastFrame/String", "Duration_LastFrame"),
    ("Duration_LastFrame/String1", "Duration_LastFrame"),
    ("Duration_LastFrame/String2", "Duration_LastFrame"),
    ("Duration_LastFrame/String3", "Duration_LastFrame"),
    ("Duration_Source", "Duration_Source"),
    ("Duration_Start", "Duration start"),
    ("ENCODER", "ENCODER"),
    ("EPG_Positions_Begin", "EPG positions begin"),
    ("EPG_Positions_End", "EPG positions end"),
    ("EditedBy", "Edited by"),
    ("EncodedBy", "Encoded by"),
    ("Encoded_Application", "Writing application"),
    ("Encoded_Application/String", "Writing application"),
    ("Encoded_Application_CompanyName", "Encoded_Application_CompanyName"),
    ("Encoded_Application_Name", "Encoded_Application_Name"),
    ("Encoded_Application_Url", "Writing application URL"),
    ("Encoded_Application_Version", "Encoded_Application_Version"),
    ("Encoded_Date", "Encoded date"),
    ("Encoded_Library", "Writing library"),
    ("Encoded_Library/String", "Writing library"),
    ("Encoded_Library_CompanyName", "Writing library company name"),
    ("Encoded_Library_Date", "Encoded_Library_Date"),
    ("Encoded_Library_Name", "Encoded_Library_Name"),
    ("Encoded_Library_Settings", "Encoding settings"),
    ("Encoded_Library_Version", "Encoded_Library_Version"),
    ("Encoded_OperatingSystem", "Encoded operating system"),
    ("Encryption", "Encryption"),
    ("Encryption_Format", "Encryption format"),
    ("Encryption_InitializationVector", "Encryption initialization vector"),
    ("Encryption_Length", "Encryption length"),
    ("Encryption_Method", "Encryption method"),
    ("Encryption_Mode", "Encryption mode"),
    ("Encryption_Padding", "Encryption padding"),
    ("ErrorDetectionType", "ErrorDetectionType"),
    ("Events_MinDuration/String", "Minimum duration per event"),
    ("Events_Total", "Count of events"),
    ("ExecutiveProducer", "Executive producer"),
    ("FileExtension", "File extension"),
    ("FileExtension_Invalid", "FileExtension_Invalid"),
    ("FileName", "File name"),
    ("FileNameExtension", "File name extension"),
    ("FileSize", "File size"),
    ("FileSize/String", "File size"),
    ("FileSize/String1", "File size"),
    ("FileSize/String2", "File size"),
    ("FileSize/String3", "File size"),
    ("FileSize/String4", "File size"),
    ("File_Created_Date", "File creation date"),
    ("File_Created_Date_Local", "File creation date (local)"),
    ("File_Modified_Date", "File last modification date"),
    ("File_Modified_Date_Local", "File last modification date (local)"),
    ("FirstPacketOrder", "FirstPacketOrder"),
    ("FolderName", "Folder name"),
    ("FooterSize", "FooterSize"),
    ("Forced", "Forced"),
    ("Forced/String", "Forced"),
    ("Format", "Format"),
    ("Format/Extensions", "Format/Extensions usually used"),
    ("Format/Info", "Format/Info"),
    ("Format/String", "Format"),
    ("Format/Url", "Format/Url"),
    ("Format_AdditionalFeatures", "Format_AdditionalFeatures"),
    ("Format_Commercial", "Commercial name"),
    ("Format_Commercial_IfAny", "Commercial name"),
    ("Format_Compression", "Format_Compression"),
    ("Format_Level", "Format level"),
    ("Format_Profile", "Format profile"),
    ("Format_Settings", "Format settings"),
    ("Format_Settings_BVOP", "Format settings, BVOP"),
    ("Format_Settings_BVOP/String", "Format settings, BVOP"),
    ("Format_Settings_CABAC", "Format settings, CABAC"),
    ("Format_Settings_CABAC/String", "Format settings, CABAC"),
    ("Format_Settings_Emphasis", "Format settings, Emphasis"),
    ("Format_Settings_Endianness", "Format settings, Endianness"),
    ("Format_Settings_Firm", "Format settings, Firm"),
    ("Format_Settings_Floor", "Format settings, Floor"),
    ("Format_Settings_FrameMode", "Format settings, Frame mode"),
    ("Format_Settings_GMC", "Format settings, GMC"),
    ("Format_Settings_GMC/String", "Format settings, GMC"),
    ("Format_Settings_GOP", "Format settings, GOP"),
    ("Format_Settings_ITU", "Format settings, ITU"),
    ("Format_Settings_Law", "Format settings, Law"),
    ("Format_Settings_Matrix", "Format settings, Matrix"),
    ("Format_Settings_Matrix/String", "Format settings, Matrix"),
    ("Format_Settings_Mode", "Mode"),
    ("Format_Settings_ModeExtension", "Format settings, Mode extension"),
    ("Format_Settings_PS/String", "Format settings, PS"),
    ("Format_Settings_Packing", "Format settings, Packing"),
    ("Format_Settings_PictureStructure", "Format settings, picture structure"),
    ("Format_Settings_Pulldown", "Format settings, pulldown"),
    ("Format_Settings_QPel", "Format settings, QPel"),
    ("Format_Settings_QPel/String", "Format settings, QPel"),
    ("Format_Settings_RefFrames", "Format settings, Reference frames"),
    ("Format_Settings_RefFrames/String", "Format settings, Reference frames"),
    ("Format_Settings_SBR", "Format settings, SBR"),
    ("Format_Settings_SBR/String", "Format settings, SBR"),
    ("Format_Settings_Sign", "Format settings, Sign"),
    ("Format_Settings_Wrapping", "Format settings, wrapping mode"),
    ("Format_Tier", "Format tier"),
    ("Format_Version", "Format version"),
    ("FrameCount", "Frame count"),
    ("FrameCount_Source", "FrameCount_Source"),
    ("FrameRate", "Frame rate"),
    ("FrameRate/String", "Frame rate"),
    ("FrameRate_Den", "Frame rate denominator"),
    ("FrameRate_Maximum", "Maximum frame rate"),
    ("FrameRate_Maximum/String", "Maximum frame rate"),
    ("FrameRate_Minimum", "Minimum frame rate"),
    ("FrameRate_Minimum/String", "Minimum frame rate"),
    ("FrameRate_Mode", "Frame rate mode"),
    ("FrameRate_Mode/String", "Frame rate mode"),
    ("FrameRate_Mode_Original", "FrameRate_Mode_Original"),
    ("FrameRate_Mode_Original/String", "Original frame rate mode"),
    ("FrameRate_Nominal/String", "Nominal frame rate"),
    ("FrameRate_Num", "Frame rate numerator"),
    ("FrameRate_Original/String", "Original frame rate"),
    ("GeneralCount", "General count"),
    ("Genre", "Genre"),
    ("Gop_OpenClosed/String", "GOP, Open/Closed"),
    ("Gop_OpenClosed_FirstFrame/String", "GOP, Open/Closed of first frame"),
    ("Grouping", "Grouping"),
    ("HDR_Format/String", "HDR format"),
    ("HeaderSize", "HeaderSize"),
    ("Height", "Height"),
    ("Height/String", "Height"),
    ("Height_CleanAperture/String", "Clean aperture height"),
    ("Height_Offset/String", "Height offset"),
    ("Height_Original/String", "Original height"),
    ("ICRA", "ICRA"),
    ("ID", "ID"),
    ("ID/String", "ID"),
    ("ISBN", "ISBN"),
    ("ISRC", "ISRC"),
    ("ImageCount", "Count of image streams"),
    ("Image_Codec_List", "Codecs Image"),
    ("Image_Format_List", "Image_Format_List"),
    ("Image_Format_WithHint_List", "Image_Format_WithHint_List"),
    ("Image_Language_List", "Image language list"),
    ("Inform", "Inform"),
    ("Interlacement/String", "Interlacement"),
    ("Interleave_Duration", "Interleave, duration"),
    ("Interleave_Duration/String", "Interleave, duration"),
    ("Interleave_Preload", "Interleave, preload duration"),
    ("Interleave_Preload/String", "Interleave, preload duration"),
    ("Interleave_VideoFrames", "Interleave, duration"),
    ("Interleaved", "Interleaved"),
    ("InternetMediaType", "Internet media type"),
    ("IsStreamable", "IsStreamable"),
    ("Keywords", "Keywords"),
    ("LCCN", "LCCN"),
    ("Label", "Label"),
    ("LabelCode", "Label code"),
    ("Language", "Language"),
    ("Language/String", "Language"),
    ("Language/String1", "Language"),
    ("Language/String2", "Language"),
    ("Language/String3", "Language"),
    ("Language/String4", "Language"),
    ("Language_More", "Language, more info"),
    ("LawRating", "Law rating"),
    ("LawRating_Reason", "Law rating reason"),
    ("Lightness", "Lightness"),
    ("List", "List"),
    ("List/String", "List"),
    ("List_StreamKind", "List_StreamKind"),
    ("List_StreamPos", "List_StreamPos"),
    ("Locked", "Locked"),
    ("Lyricist", "Lyricist"),
    ("Lyrics", "Lyrics"),
    ("MasteredBy", "Mastered by"),
    ("Mastered_Date", "Mastered date"),
    ("MasteringDisplay_ColorPrimaries", "Mastering display color primaries"),
    ("MasteringDisplay_Luminance", "Mastering display luminance"),
    ("Matrix_Channel(s)/String", "Matrix channel(s)"),
    ("Matrix_ChannelPositions", "Matrix channel positions"),
    ("Matrix_Format", "Matrix format"),
    ("MaxCLL", "Maximum Content Light Level"),
    ("MaxFALL", "Maximum Frame-Average Light Level"),
    ("Menu For", "Menu For"),
    ("MenuCount", "Count of menu streams"),
    ("MenuID", "Menu ID"),
    ("MenuID/String", "Menu ID"),
    ("Menu_Codec_List", "Menu codecs"),
    ("Menu_Format_List", "Menu_Format_List"),
    ("Menu_Format_WithHint_List", "Menu_Format_WithHint_List"),
    ("Menu_Language_List", "Menu_Language_List"),
    ("Menus", "Menus"),
    ("Mood", "Mood"),
    ("Movie", "Movie name"),
    ("Movie/Country", "Movie country"),
    ("Movie/Url", "Movie URL"),
    ("Movie_More", "Movie name, more info"),
    ("MultiView_Count", "Multiview count"),
    ("MultiView_Layout", "Multiview layout"),
    ("MusicBy", "Music by"),
    ("MuxingMode", "Muxing mode"),
    ("MuxingMode_MoreInfo", "Muxing mode, more info"),
    ("NetworkName", "Network name"),
    ("Original/Album", "Original album"),
    ("Original/Lyricist", "Original lyricist"),
    ("Original/Movie", "Original movie"),
    ("Original/Part", "Original part"),
    ("Original/Performer", "Original performer"),
    ("Original/Released_Date", "Original released date"),
    ("Original/Track", "Original track"),
    ("OriginalNetworkName", "Original network name"),
    ("OriginalSourceForm", "Original source form"),
    ("OriginalSourceForm/Cropped", "Original source form cropped"),
    ("OriginalSourceForm/DistributedBy", "Original source form distributed by"),
    ("OriginalSourceForm/Name", "Original source form name"),
    ("OriginalSourceForm/NumColors", "Original source form number of colors"),
    ("OriginalSourceForm/Sharpness", "Original source form sharpness"),
    ("OriginalSourceMedium", "Original source medium"),
    ("OriginalSourceMedium_ID/String", "Original source medium ID"),
    ("OtherCount", "OtherCount"),
    ("Other_Codec_List", "Other_Codec_List"),
    ("Other_Format_List", "Other_Format_List"),
    ("Other_Format_WithHint_List", "Other_Format_WithHint_List"),
    ("Other_Language_List", "Other language list"),
    ("OverallBitRate", "Overall bit rate"),
    ("OverallBitRate/String", "Overall bit rate"),
    ("OverallBitRate_Maximum", "Maximum Overall bit rate"),
    ("OverallBitRate_Maximum/String", "Maximum Overall bit rate"),
    ("OverallBitRate_Minimum/String", "Minimum Overall bit rate"),
    ("OverallBitRate_Mode", "Overall bit rate mode"),
    ("OverallBitRate_Mode/String", "Overall bit rate mode"),
    ("OverallBitRate_Nominal/String", "Nominal Overall bit rate"),
    ("OverallBitRate_Precision_Max", "OverallBitRate_Precision_Max"),
    ("OverallBitRate_Precision_Min", "OverallBitRate_Precision_Min"),
    ("Owner", "Owner"),
    ("PackageName", "Package name"),
    ("Part", "Part"),
    ("Part/Position", "Part position"),
    ("Part/Position_Total", "Part position total"),
    ("Performer", "Performer"),
    ("Performer/Sort", "Performer sort"),
    ("Performer/Url", "Performer URL"),
    ("Period", "Period"),
    ("PixelAspectRatio", "Pixel aspect ratio"),
    ("PixelAspectRatio/String", "Pixel aspect ratio"),
    ("PixelAspectRatio_CleanAperture/String", "Clean aperture pixel aspect ratio"),
    ("PixelAspectRatio_Original/String", "Original pixel aspect ratio"),
    ("Played_Count", "Played count"),
    ("Played_First_Date", "Played first date"),
    ("Played_Last_Date", "Played last date"),
    ("PodcastCategory", "Podcast category"),
    ("Producer", "Producer"),
    ("Producer_Copyright", "Producer copyright"),
    ("ProductionDesigner", "Production designer"),
    ("ProductionStudio", "Production studio"),
    ("Publisher", "Publisher"),
    ("Publisher/URL", "Publisher URL"),
    ("Rating", "Rating"),
    ("Recorded_Date", "Recorded date"),
    ("Recorded_Location", "Recorded location"),
    ("Released_Date", "Released date"),
    ("RemixedBy", "Remixed by"),
    ("ReplayGain_Gain/String", "Replay gain"),
    ("ReplayGain_Peak", "Replay gain peak"),
    ("Resolution/String", "Resolution"),
    ("Rotation", "Rotation"),
    ("Rotation/String", "Rotation"),
    ("Sampled_Height", "Sampled_Height"),
    ("Sampled_Width", "Sampled_Width"),
    ("SamplesPerFrame", "Samples per frame"),
    ("SamplingCount", "Samples count"),
    ("SamplingCount_Source", "SamplingCount_Source"),
    ("SamplingRate", "Sampling rate"),
    ("SamplingRate/String", "Sampling rate"),
    ("ScanOrder", "Scan order"),
    ("ScanOrder/String", "Scan order"),
    ("ScanOrder_Original/String", "Original scan order"),
    ("ScanOrder_Stored/String", "Scan order, stored"),
    ("ScanOrder_StoredDisplayedInverted", "Scan order, stored/displayed inverted"),
    ("ScanType", "Scan type"),
    ("ScanType/String", "Scan type"),
    ("ScanType_Original/String", "Original scan type"),
    ("ScanType_StoreMethod/String", "Scan type, store method"),
    ("ScreenplayBy", "Screenplay by"),
    ("Season", "Season"),
    ("Season_Position", "Season position"),
    ("Season_Position_Total", "Season position total"),
    ("Service/Url", "Service URL"),
    ("ServiceChannel", "Service channel"),
    ("ServiceKind", "Service kind"),
    ("ServiceKind/String", "Service kind"),
    ("ServiceName", "Service name"),
    ("ServiceProvider", "Service provider"),
    ("ServiceProvider/Url", "Service provider URL"),
    ("ServiceType", "Service type"),
    ("SoundEngineer", "Sound engineer"),
    ("Source_Delay", "Source_Delay"),
    ("Source_Delay_Source", "Source_Delay_Source"),
    ("Source_Duration", "Source duration"),
    ("Source_Duration/String", "Source duration"),
    ("Source_Duration/String1", "Source duration"),
    ("Source_Duration/String2", "Source duration"),
    ("Source_Duration/String3", "Source duration"),
    ("Source_Duration_FirstFrame/String", "Source_Duration_FirstFrame"),
    ("Source_Duration_LastFrame", "Source_Duration_LastFrame"),
    ("Source_Duration_LastFrame/String", "Source_Duration_LastFrame"),
    ("Source_Duration_LastFrame/String1", "Source_Duration_LastFrame"),
    ("Source_Duration_LastFrame/String2", "Source_Duration_LastFrame"),
    ("Source_Duration_LastFrame/String3", "Source_Duration_LastFrame"),
    ("Source_FrameCount", "Source frame count"),
    ("Source_StreamSize", "Source stream size"),
    ("Source_StreamSize/String", "Source stream size"),
    ("Source_StreamSize/String1", "Source stream size"),
    ("Source_StreamSize/String2", "Source stream size"),
    ("Source_StreamSize/String3", "Source stream size"),
    ("Source_StreamSize/String4", "Source stream size"),
    ("Source_StreamSize/String5", "Source stream size"),
    ("Source_StreamSize_Encoded/String", "Source encoded stream size"),
    ("Source_StreamSize_Proportion", "Source_StreamSize_Proportion"),
    ("Standard", "Standard"),
    ("Status", "Status"),
    ("Stored_Height", "Stored height"),
    ("Stored_Width", "Stored width"),
    ("StreamCount", "Count of stream of this kind"),
    ("StreamKind", "Kind of stream"),
    ("StreamKind/String", "Kind of stream"),
    ("StreamKindID", "Stream identifier"),
    ("StreamKindPos", "Stream identifier"),
    ("StreamOrder", "StreamOrder"),
    ("StreamSize", "Stream size"),
    ("StreamSize/String", "Stream size"),
    ("StreamSize/String1", "Stream size"),
    ("StreamSize/String2", "Stream size"),
    ("StreamSize/String3", "Stream size"),
    ("StreamSize/String4", "Stream size"),
    ("StreamSize/String5", "Stream size"),
    ("StreamSize_Demuxed/String", "Stream size demuxed"),
    ("StreamSize_Encoded/String", "Encoded stream size"),
    ("StreamSize_Proportion", "Proportion of this stream"),
    ("SubTrack", "Sub track"),
    ("Subject", "Subject"),
    ("Summary", "Summary"),
    ("Synopsis", "Synopsis"),
    ("Tagged_Application", "Tagged application"),
    ("Tagged_Date", "Tagged date"),
    ("TermsOfUse", "Terms of use"),
    ("TextCount", "Count of text streams"),
    ("Text_Codec_List", "Text codecs"),
    ("Text_Format_List", "Text_Format_List"),
    ("Text_Format_WithHint_List", "Text_Format_WithHint_List"),
    ("Text_Language_List", "Text_Language_List"),
    ("ThanksTo", "Thanks to"),
    ("TimeCode_FirstFrame", "Time code of first frame"),
    ("TimeCode_FirstFrame/String", "Time code of first frame"),
    ("TimeCode_Settings", "Time code settings"),
    ("TimeCode_Source", "Time code source"),
    ("TimeCode_Striped", "Time code, striped"),
    ("TimeCode_Striped/String", "Time code, striped"),
    ("TimeStamp_FirstFrame/String", "Time stamp of first frame"),
    ("TimeZone", "Time zone"),
    ("Title", "Title"),
    ("Track", "Track name"),
    ("Track/Position", "Track name/Position"),
    ("Track/Position_Total", "Track name/Total"),
    ("Track/Sort", "Track name sort"),
    ("Track/Url", "Track URL"),
    ("Track_More", "Track name, more info"),
    ("Type", "Type"),
    ("UniqueID", "Unique ID"),
    ("UniqueID/String", "Unique ID"),
    ("UniversalAdID/String", "Universal Ad-ID"),
    ("Video0_Delay/String", "Video0 delay"),
    ("VideoCount", "Count of video streams"),
    ("Video_Codec_List", "Codecs Video"),
    ("Video_Delay", "Delay relative to video"),
    ("Video_Delay/String", "Delay relative to video"),
    ("Video_Delay/String1", "Delay relative to video"),
    ("Video_Delay/String2", "Delay relative to video"),
    ("Video_Delay/String3", "Delay relative to video"),
    ("Video_Format_List", "Video_Format_List"),
    ("Video_Format_WithHint_List", "Video_Format_WithHint_List"),
    ("Video_Language_List", "Video language list"),
    ("WM/EncodingSettings", "WM/EncodingSettings"),
    ("Width", "Width"),
    ("Width/String", "Width"),
    ("Width_CleanAperture/String", "Clean aperture width"),
    ("Width_Offset/String", "Width offset"),
    ("Width_Original/String", "Original width"),
    ("WrittenBy", "Written by"),
    ("Written_Date", "Written date"),
    ("Written_Location", "Written location"),
    ("acmod", "acmod"),
    ("bsid", "bsid"),
    ("colour_description_present", "colour_description_present"),
    ("colour_description_present_Source", "colour_description_present_Source"),
    ("colour_primaries", "Color primaries"),
    ("colour_range", "Color range"),
    ("colour_range_Source", "colour_range_Source"),
    ("dialnorm", "Dialog Normalization"),
    ("dialnorm/String", "Dialog Normalization"),
    ("dialnorm_Average", "dialnorm_Average"),
    ("dialnorm_Average/String", "dialnorm_Average"),
    ("dialnorm_Count", "dialnorm_Count"),
    ("dialnorm_Maximum", "dialnorm_Maximum"),
    ("dialnorm_Maximum/String", "dialnorm_Maximum"),
    ("dialnorm_Minimum", "dialnorm_Minimum"),
    ("dialnorm_Minimum/String", "dialnorm_Minimum"),
    ("encoder", "encoder"),
    ("format_identifier", "format_identifier"),
    ("intra_dc_precision", "intra_dc_precision"),
    ("lfeon", "lfeon"),
    ("matrix_coefficients", "Matrix coefficients"),
    ("pointer_field", "pointer_field"),
    ("section_length", "section_length"),
    ("transfer_characteristics", "Transfer characteristics"),
];

/// Text-report label for a field name; the raw name when there is no translation.
pub fn label(name: &str) -> &str {
    static MAP: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();
    let map = MAP.get_or_init(|| LABELS.iter().copied().collect());
    match map.get(name) {
        Some(l) => l,
        None => match name.strip_suffix("/String") {
            Some(base) => map.get(base).copied().unwrap_or(name),
            None => name,
        },
    }
}
