// Generated from tests/oracle/_schema.tsv (reference MediaInfoLib v20.08 field tables).
// (name, measure, options). Options: [0] show in Inform, [2] show in Supported/Full, [3] value type (T/I/F/D/B/N), [4] in XML/JSON.

pub static GENERAL: &[(&str, &str, &str)] = &[
    ("Count", "", "N NI"),
    ("Status", "", "N NI"),
    ("StreamCount", "", "N NI"),
    ("StreamKind", "", "N NT"),
    ("StreamKind/String", "", "N NT"),
    ("StreamKindID", "", "N NI"),
    ("StreamKindPos", "", "N NI"),
    ("StreamOrder", "", "N YIY"),
    ("FirstPacketOrder", "", "N YI"),
    ("Inform", "", "N NT"),
    ("ID", "", "N YTY"),
    ("ID/String", "", "Y NT"),
    ("OriginalSourceMedium_ID", "", "N YTY"),
    ("OriginalSourceMedium_ID/String", "", "Y NT"),
    ("UniqueID", "", "N YTY"),
    ("UniqueID/String", "", "Y NT"),
    ("MenuID", "", "N YTY"),
    ("MenuID/String", "", "Y NT"),
    ("GeneralCount", "", "N NIY"),
    ("VideoCount", "", "N NIY"),
    ("AudioCount", "", "N NIY"),
    ("TextCount", "", "N NIY"),
    ("OtherCount", "", "N NIY"),
    ("ImageCount", "", "N NIY"),
    ("MenuCount", "", "N NIY"),
    ("Video_Format_List", "", "N NT"),
    ("Video_Format_WithHint_List", "", "N NT"),
    ("Video_Codec_List", "", "N NT"),
    ("Video_Language_List", "", "N NT"),
    ("Audio_Format_List", "", "N NT"),
    ("Audio_Format_WithHint_List", "", "N NT"),
    ("Audio_Codec_List", "", "N NT"),
    ("Audio_Language_List", "", "N NT"),
    ("Text_Format_List", "", "N NT"),
    ("Text_Format_WithHint_List", "", "N NT"),
    ("Text_Codec_List", "", "N NT"),
    ("Text_Language_List", "", "N NT"),
    ("Other_Format_List", "", "N NT"),
    ("Other_Format_WithHint_List", "", "N NT"),
    ("Other_Codec_List", "", "N NT"),
    ("Other_Language_List", "", "N NT"),
    ("Image_Format_List", "", "N NT"),
    ("Image_Format_WithHint_List", "", "N NT"),
    ("Image_Codec_List", "", "N NT"),
    ("Image_Language_List", "", "N NT"),
    ("Menu_Format_List", "", "N NT"),
    ("Menu_Format_WithHint_List", "", "N NT"),
    ("Menu_Codec_List", "", "N NT"),
    ("Menu_Language_List", "", "N NT"),
    ("CompleteName", "", "Y YT"),
    ("FolderName", "", "N NT"),
    ("FileNameExtension", "", "N NT"),
    ("FileName", "", "N NT"),
    ("FileExtension", "", "N NTY"),
    ("CompleteName_Last", "", "Y YTY"),
    ("FolderName_Last", "", "N NT"),
    ("FileNameExtension_Last", "", "N NT"),
    ("FileName_Last", "", "N NT"),
    ("FileExtension_Last", "", "N NT"),
    ("Format", "", "N YTY"),
    ("Format/String", "", "Y NT"),
    ("Format/Info", "", "Y NT"),
    ("Format/Url", "", "N NT"),
    ("Format/Extensions", "", "N NT"),
    ("Format_Commercial", "", "N NT"),
    ("Format_Commercial_IfAny", "", "Y YTY"),
    ("Format_Version", "", "Y YTY"),
    ("Format_Profile", "", "Y YTY"),
    ("Format_Level", "", "Y YTY"),
    ("Format_Compression", "", "Y YTY"),
    ("Format_Settings", "", "Y YTY"),
    ("Format_AdditionalFeatures", "", "N YTY"),
    ("InternetMediaType", "", "N YT"),
    ("CodecID", "", "N YTY"),
    ("CodecID/String", "", "Y NT"),
    ("CodecID/Info", "", "Y NT"),
    ("CodecID/Hint", "", "Y NT"),
    ("CodecID/Url", "", "N NT"),
    ("CodecID_Description", "", "Y YTY"),
    ("CodecID_Version", "", "N YTY"),
    ("CodecID_Compatible", "", "N YTY"),
    ("Interleaved", "", "N YTY"),
    ("Codec", "", "N NT"),
    ("Codec/String", "", "N NT"),
    ("Codec/Info", "", "N NT"),
    ("Codec/Url", "", "N NT"),
    ("Codec/Extensions", "", "N NT"),
    ("Codec_Settings", "", "N NT"),
    ("Codec_Settings_Automatic", "", "N NT"),
    ("FileSize", " byte", "N YTY"),
    ("FileSize/String", "", "Y NT"),
    ("FileSize/String1", "", "N NT"),
    ("FileSize/String2", "", "N NT"),
    ("FileSize/String3", "", "N NT"),
    ("FileSize/String4", "", "N NT"),
    ("Duration", " ms", "N YFY"),
    ("Duration/String", "", "Y NT"),
    ("Duration/String1", "", "N NT"),
    ("Duration/String2", "", "N NT"),
    ("Duration/String3", "", "N NT"),
    ("Duration/String4", "", "N NT"),
    ("Duration/String5", "", "N NT"),
    ("Duration_Start", "", "Y YTY"),
    ("Duration_End", "", "Y YTY"),
    ("OverallBitRate_Mode", "", "N YTY"),
    ("OverallBitRate_Mode/String", "", "Y NT"),
    ("OverallBitRate", " bps", "N YFY"),
    ("OverallBitRate/String", "", "Y NT"),
    ("OverallBitRate_Minimum", " bps", "N YFY"),
    ("OverallBitRate_Minimum/String", "", "Y NT"),
    ("OverallBitRate_Nominal", " bps", "N YFY"),
    ("OverallBitRate_Nominal/String", "", "Y NT"),
    ("OverallBitRate_Maximum", " bps", "N YFY"),
    ("OverallBitRate_Maximum/String", "", "Y NT"),
    ("FrameRate", " fps", "N YFY"),
    ("FrameRate/String", "", "N NT"),
    ("FrameRate_Num", "", "N NFN"),
    ("FrameRate_Den", "", "N NFN"),
    ("FrameCount", "", "N NIY"),
    ("Delay", " ms", "N YI"),
    ("Delay/String", "", "N NT"),
    ("Delay/String1", "", "N NT"),
    ("Delay/String2", "", "N NT"),
    ("Delay/String3", "", "N NT"),
    ("Delay/String4", "", "N NT"),
    ("Delay/String5", "", "N NT"),
    ("Delay_Settings", "", "N NTY"),
    ("Delay_DropFrame", "", "N NTY"),
    ("Delay_Source", "", "N NTY"),
    ("Delay_Source/String", "", "N NT"),
    ("StreamSize", " byte", "N YIY"),
    ("StreamSize/String", "", "N NT"),
    ("StreamSize/String1", "", "N NT"),
    ("StreamSize/String2", "", "N NT"),
    ("StreamSize/String3", "", "N NT"),
    ("StreamSize/String4", "", "N NT"),
    ("StreamSize/String5", "", "N NT"),
    ("StreamSize_Proportion", "", "N NT"),
    ("StreamSize_Demuxed", " byte", "N YIN"),
    ("StreamSize_Demuxed/String", "", "N NT"),
    ("StreamSize_Demuxed/String1", "", "N NT"),
    ("StreamSize_Demuxed/String2", "", "N NT"),
    ("StreamSize_Demuxed/String3", "", "N NT"),
    ("StreamSize_Demuxed/String4", "", "N NT"),
    ("StreamSize_Demuxed/String5", "", "N NT"),
    ("HeaderSize", "", "N YIY"),
    ("DataSize", "", "N YIY"),
    ("FooterSize", "", "N YIY"),
    ("IsStreamable", "", "N YTY"),
    ("Album_ReplayGain_Gain", " dB", "N YTY"),
    ("Album_ReplayGain_Gain/String", "", "Y YT"),
    ("Album_ReplayGain_Peak", "", "Y YTY"),
    ("Encryption", "", "Y YT"),
    ("Encryption_Format", "", "N YTY"),
    ("Encryption_Length", "", "N YTY"),
    ("Encryption_Method", "", "N YTY"),
    ("Encryption_Mode", "", "N YTY"),
    ("Encryption_Padding", "", "N YTY"),
    ("Encryption_InitializationVector", "", "N YTY"),
    ("UniversalAdID/String", "", "Y NT"),
    ("UniversalAdID_Registry", "", "N YTY"),
    ("UniversalAdID_Value", "", "N YTY"),
    ("Title", "", "N NTY"),
    ("Title_More", "", "N NTY"),
    ("Title/Url", "", "N NT"),
    ("Domain", "", "Y YTY"),
    ("Collection", "", "Y YTY"),
    ("Season", "", "Y YTY"),
    ("Season_Position", "", "Y YIY"),
    ("Season_Position_Total", "", "Y YIY"),
    ("Movie", "", "Y YTY"),
    ("Movie_More", "", "Y YTY"),
    ("Movie/Country", "", "Y YTY"),
    ("Movie/Url", "", "Y YT"),
    ("Album", "", "Y YTY"),
    ("Album_More", "", "Y YTY"),
    ("Album/Sort", "", "Y YTY"),
    ("Album/Performer", "", "Y YTY"),
    ("Album/Performer/Sort", "", "Y YTY"),
    ("Album/Performer/Url", "", "Y YT"),
    ("Comic", "", "Y YTY"),
    ("Comic_More", "", "Y YTY"),
    ("Comic/Position_Total", "", "Y YIY"),
    ("Part", "", "Y YTY"),
    ("Part/Position", "", "Y YIY"),
    ("Part/Position_Total", "", "Y YIY"),
    ("Track", "", "Y YTY"),
    ("Track_More", "", "Y YTY"),
    ("Track/Url", "", "Y YT"),
    ("Track/Sort", "", "Y YTY"),
    ("Track/Position", "", "Y YIY"),
    ("Track/Position_Total", "", "Y YIY"),
    ("PackageName", "", "Y YTY"),
    ("Grouping", "", "Y YTY"),
    ("Chapter", "", "Y YTY"),
    ("SubTrack", "", "Y YTY"),
    ("Original/Album", "", "Y YTY"),
    ("Original/Movie", "", "Y YTY"),
    ("Original/Part", "", "Y YTY"),
    ("Original/Track", "", "Y YTY"),
    ("Compilation", "Yes", "N YTY"),
    ("Compilation/String", "", "Y NT"),
    ("Performer", "", "Y YTY"),
    ("Performer/Sort", "", "Y YTY"),
    ("Performer/Url", "", "Y YT"),
    ("Original/Performer", "", "Y YTY"),
    ("Accompaniment", "", "Y YTY"),
    ("Composer", "", "Y YTY"),
    ("Composer/Nationality", "", "Y YTY"),
    ("Composer/Sort", "", "Y YTY"),
    ("Arranger", "", "Y YTY"),
    ("Lyricist", "", "Y YTY"),
    ("Original/Lyricist", "", "Y YTY"),
    ("Conductor", "", "Y YTY"),
    ("Director", "", "Y YTY"),
    ("CoDirector", "", "Y YTY"),
    ("AssistantDirector", "", "Y YTY"),
    ("DirectorOfPhotography", "", "Y YTY"),
    ("SoundEngineer", "", "Y YTY"),
    ("ArtDirector", "", "Y YTY"),
    ("ProductionDesigner", "", "Y YTY"),
    ("Choreographer", "", "Y YTY"),
    ("CostumeDesigner", "", "Y YTY"),
    ("Actor", "", "Y YTY"),
    ("Actor_Character", "", "Y YTY"),
    ("WrittenBy", "", "Y YTY"),
    ("ScreenplayBy", "", "Y YTY"),
    ("EditedBy", "", "Y YTY"),
    ("CommissionedBy", "", "Y YTY"),
    ("Producer", "", "Y YTY"),
    ("CoProducer", "", "Y YTY"),
    ("ExecutiveProducer", "", "Y YTY"),
    ("MusicBy", "", "Y YTY"),
    ("DistributedBy", "", "Y YTY"),
    ("OriginalSourceForm/DistributedBy", "", "Y YTY"),
    ("MasteredBy", "", "Y YTY"),
    ("EncodedBy", "", "Y YTY"),
    ("RemixedBy", "", "Y YTY"),
    ("ProductionStudio", "", "Y YTY"),
    ("ThanksTo", "", "Y YTY"),
    ("Publisher", "", "Y YTY"),
    ("Publisher/URL", "", "Y YTY"),
    ("Label", "", "Y YTY"),
    ("Genre", "", "Y YTY"),
    ("PodcastCategory", "", "Y YTY"),
    ("Mood", "", "Y YTY"),
    ("ContentType", "", "Y YTY"),
    ("Subject", "", "Y YTY"),
    ("Description", "", "Y YTY"),
    ("Keywords", "", "Y YTY"),
    ("Summary", "", "Y YTY"),
    ("Synopsis", "", "Y YTY"),
    ("Period", "", "Y YTY"),
    ("LawRating", "", "Y YTY"),
    ("LawRating_Reason", "", "Y YTY"),
    ("ICRA", "", "Y YTY"),
    ("Released_Date", "", "Y YTY"),
    ("Original/Released_Date", "", "Y YTY"),
    ("Recorded_Date", "", "Y YTY"),
    ("Encoded_Date", "", "Y YTY"),
    ("Tagged_Date", "", "Y YTY"),
    ("Written_Date", "", "Y YTY"),
    ("Mastered_Date", "", "Y YTY"),
    ("File_Created_Date", "", "N NTY"),
    ("File_Created_Date_Local", "", "N NTY"),
    ("File_Modified_Date", "", "N NTY"),
    ("File_Modified_Date_Local", "", "N NTY"),
    ("Recorded_Location", "", "Y YTY"),
    ("Written_Location", "", "Y YTY"),
    ("Archival_Location", "", "Y YTY"),
    ("Encoded_Application", "", "N YTY"),
    ("Encoded_Application/String", "", "Y NT"),
    ("Encoded_Application_CompanyName", "", "N YTY"),
    ("Encoded_Application_Name", "", "N YTY"),
    ("Encoded_Application_Version", "", "N YTY"),
    ("Encoded_Application_Url", "", "N YTY"),
    ("Encoded_Library", "", "N YTY"),
    ("Encoded_Library/String", "", "Y NT"),
    ("Encoded_Library_CompanyName", "", "N YTY"),
    ("Encoded_Library_Name", "", "N NTY"),
    ("Encoded_Library_Version", "", "N NTY"),
    ("Encoded_Library_Date", "", "N NTY"),
    ("Encoded_Library_Settings", "", "Y YTY"),
    ("Encoded_OperatingSystem", "", "N YTY"),
    ("Cropped", "", "Y YTY"),
    ("Dimensions", "", "Y YTY"),
    ("DotsPerInch", "", "Y YTY"),
    ("Lightness", "", "Y YTY"),
    ("OriginalSourceMedium", "", "Y YTY"),
    ("OriginalSourceForm", "", "Y YTY"),
    ("OriginalSourceForm/NumColors", "", "Y YTY"),
    ("OriginalSourceForm/Name", "", "Y YTY"),
    ("OriginalSourceForm/Cropped", "", "Y YTY"),
    ("OriginalSourceForm/Sharpness", "", "Y YTY"),
    ("Tagged_Application", "", "Y YTY"),
    ("BPM", "", "Y YTY"),
    ("ISRC", "", "Y YTY"),
    ("ISBN", "", "Y YTY"),
    ("BarCode", "", "Y YTY"),
    ("LCCN", "", "Y YTY"),
    ("CatalogNumber", "", "Y YTY"),
    ("LabelCode", "", "Y YTY"),
    ("Owner", "", "Y YTY"),
    ("Copyright", "", "Y YTY"),
    ("Copyright/Url", "", "Y YTY"),
    ("Producer_Copyright", "", "Y YTY"),
    ("TermsOfUse", "", "Y YTY"),
    ("ServiceName", "", "Y YTY"),
    ("ServiceChannel", "", "Y YTY"),
    ("Service/Url", "", "Y YTY"),
    ("ServiceProvider", "", "Y YTY"),
    ("ServiceProvider/Url", "", "Y YTN"),
    ("ServiceType", "", "Y YTY"),
    ("NetworkName", "", "Y YTY"),
    ("OriginalNetworkName", "", "Y YTY"),
    ("Country", "", "Y YTY"),
    ("TimeZone", "", "Y YTY"),
    ("Cover", "", "Y YTY"),
    ("Cover_Description", "", "Y YTY"),
    ("Cover_Type", "", "Y YTY"),
    ("Cover_Mime", "", "Y YTY"),
    ("Cover_Data", "", "N YTY"),
    ("Lyrics", "", "Y YTY"),
    ("Comment", "", "Y YTY"),
    ("Rating", "", "Y YTY"),
    ("Added_Date", "", "Y YTY"),
    ("Played_First_Date", "", "Y YTY"),
    ("Played_Last_Date", "", "Y YTY"),
    ("Played_Count", "", "Y YIY"),
    ("EPG_Positions_Begin", "", "N YIY"),
    ("EPG_Positions_End", "", "N YIY"),
];

pub static VIDEO: &[(&str, &str, &str)] = &[
    ("Count", "", "N NI"),
    ("Status", "", "N NI"),
    ("StreamCount", "", "N NI"),
    ("StreamKind", "", "N NT"),
    ("StreamKind/String", "", "N NT"),
    ("StreamKindID", "", "N NI"),
    ("StreamKindPos", "", "N NI"),
    ("StreamOrder", "", "N YIY"),
    ("FirstPacketOrder", "", "N YIY"),
    ("Inform", "", "N NT"),
    ("ID", "", "N YTY"),
    ("ID/String", "", "Y NT"),
    ("OriginalSourceMedium_ID", "", "N YTY"),
    ("OriginalSourceMedium_ID/String", "", "Y NT"),
    ("UniqueID", "", "N YTY"),
    ("UniqueID/String", "", "Y NT"),
    ("MenuID", "", "N YTY"),
    ("MenuID/String", "", "Y NT"),
    ("Format", "", "N YTY"),
    ("Format/String", "", "Y NT"),
    ("Format/Info", "", "Y NT"),
    ("Format/Url", "", "N NT"),
    ("Format_Commercial", "", "N NT"),
    ("Format_Commercial_IfAny", "", "Y YTY"),
    ("Format_Version", "", "Y YTY"),
    ("Format_Profile", "", "Y YTY"),
    ("Format_Level", "", "Y YTY"),
    ("Format_Tier", "", "Y YTY"),
    ("Format_Compression", "", "Y YTY"),
    ("Format_AdditionalFeatures", "", "N YTY"),
    ("MultiView_BaseProfile", "", "Y YTY"),
    ("MultiView_Count", "", "Y YTY"),
    ("MultiView_Layout", "", "Y YTY"),
    ("HDR_Format", "", "N YTY"),
    ("HDR_Format/String", "", "Y NT"),
    ("HDR_Format_Commercial", "", "N NT"),
    ("HDR_Format_Version", "", "N YTY"),
    ("HDR_Format_Profile", "", "N YTY"),
    ("HDR_Format_Level", "", "N YTY"),
    ("HDR_Format_Settings", "", "N YTY"),
    ("HDR_Format_Compatibility", "", "N YTY"),
    ("Format_Settings", "", "Y NT"),
    ("Format_Settings_BVOP", "Yes", "N YTY"),
    ("Format_Settings_BVOP/String", "", "Y NT"),
    ("Format_Settings_QPel", "Yes", "N YTY"),
    ("Format_Settings_QPel/String", "", "Y NT"),
    ("Format_Settings_GMC", " warppoint", "N YIY"),
    ("Format_Settings_GMC/String", "", "Y NT"),
    ("Format_Settings_Matrix", "", "N YTY"),
    ("Format_Settings_Matrix/String", "", "Y NT"),
    ("Format_Settings_Matrix_Data", "", "N NTY"),
    ("Format_Settings_CABAC", "Yes", "N YTY"),
    ("Format_Settings_CABAC/String", "", "Y NT"),
    ("Format_Settings_RefFrames", " frame", "N YIY"),
    ("Format_Settings_RefFrames/String", "", "Y NT"),
    ("Format_Settings_Pulldown", "", "Y YTY"),
    ("Format_Settings_Endianness", "", "N YTY"),
    ("Format_Settings_Packing", "", "N YTY"),
    ("Format_Settings_FrameMode", "", "Y YTY"),
    ("Format_Settings_GOP", "", "Y YTY"),
    ("Format_Settings_PictureStructure", "", "Y YTY"),
    ("Format_Settings_Wrapping", "", "Y YTY"),
    ("InternetMediaType", "", "N YT"),
    ("MuxingMode", "", "Y YTY"),
    ("CodecID", "", "Y YTY"),
    ("CodecID/String", "", "Y NT"),
    ("CodecID/Info", "", "Y NT"),
    ("CodecID/Hint", "", "Y NT"),
    ("CodecID/Url", "", "N NT"),
    ("CodecID_Description", "", "Y YT"),
    ("Codec", "", "N NT"),
    ("Codec/String", "", "N NT"),
    ("Codec/Family", "", "N NT"),
    ("Codec/Info", "", "N NT"),
    ("Codec/Url", "", "N NT"),
    ("Codec/CC", "", "N NT"),
    ("Codec_Profile", "", "N NT"),
    ("Codec_Description", "", "N NT"),
    ("Codec_Settings", "", "N NT"),
    ("Codec_Settings_PacketBitStream", "", "N NT"),
    ("Codec_Settings_BVOP", "", "N NT"),
    ("Codec_Settings_QPel", "", "N NT"),
    ("Codec_Settings_GMC", " warppoint", "N NT"),
    ("Codec_Settings_GMC/String", "", "N NT"),
    ("Codec_Settings_Matrix", "", "N NT"),
    ("Codec_Settings_Matrix_Data", "", "N NT"),
    ("Codec_Settings_CABAC", "", "N NT"),
    ("Codec_Settings_RefFrames", "", "N NT"),
    ("Duration", " ms", "N YFY"),
    ("Duration/String", "", "Y NT"),
    ("Duration/String1", "", "N NT"),
    ("Duration/String2", "", "N NT"),
    ("Duration/String3", "", "N NT"),
    ("Duration/String4", "", "N NT"),
    ("Duration/String5", "", "N NT"),
    ("Duration_FirstFrame", " ms", "N YFY"),
    ("Duration_FirstFrame/String", "", "Y NT"),
    ("Duration_FirstFrame/String1", "", "N NT"),
    ("Duration_FirstFrame/String2", "", "N NT"),
    ("Duration_FirstFrame/String3", "", "N NT"),
    ("Duration_FirstFrame/String4", "", "N NT"),
    ("Duration_FirstFrame/String5", "", "N NT"),
    ("Duration_LastFrame", " ms", "N YFY"),
    ("Duration_LastFrame/String", "", "Y NT"),
    ("Duration_LastFrame/String1", "", "N NT"),
    ("Duration_LastFrame/String2", "", "N NT"),
    ("Duration_LastFrame/String3", "", "N NT"),
    ("Duration_LastFrame/String4", "", "N NT"),
    ("Duration_LastFrame/String5", "", "N NT"),
    ("Source_Duration", " ms", "N YFY"),
    ("Source_Duration/String", "", "Y NT"),
    ("Source_Duration/String1", "", "N NT"),
    ("Source_Duration/String2", "", "N NT"),
    ("Source_Duration/String3", "", "N NT"),
    ("Source_Duration/String4", "", "N NT"),
    ("Source_Duration/String5", "", "N NT"),
    ("Source_Duration_FirstFrame", " ms", "N YFY"),
    ("Source_Duration_FirstFrame/String", "", "Y NT"),
    ("Source_Duration_FirstFrame/String1", "", "N NT"),
    ("Source_Duration_FirstFrame/String2", "", "N NT"),
    ("Source_Duration_FirstFrame/String3", "", "N NT"),
    ("Source_Duration_FirstFrame/String4", "", "N NT"),
    ("Source_Duration_FirstFrame/String5", "", "N NT"),
    ("Source_Duration_LastFrame", " ms", "N YFY"),
    ("Source_Duration_LastFrame/String", "", "Y NT"),
    ("Source_Duration_LastFrame/String1", "", "N NT"),
    ("Source_Duration_LastFrame/String2", "", "N NT"),
    ("Source_Duration_LastFrame/String3", "", "N NT"),
    ("Source_Duration_LastFrame/String4", "", "N NT"),
    ("Source_Duration_LastFrame/String5", "", "N NT"),
    ("BitRate_Mode", "", "N YTY"),
    ("BitRate_Mode/String", "", "Y NT"),
    ("BitRate", " bps", "N YFY"),
    ("BitRate/String", "", "Y NT"),
    ("BitRate_Minimum", " bps", "N YFY"),
    ("BitRate_Minimum/String", "", "Y NT"),
    ("BitRate_Nominal", " bps", "N YFY"),
    ("BitRate_Nominal/String", "", "Y NT"),
    ("BitRate_Maximum", " bps", "N YFY"),
    ("BitRate_Maximum/String", "", "Y NT"),
    ("BitRate_Encoded", " bps", "N YFY"),
    ("BitRate_Encoded/String", "", "N NT"),
    ("Width", " pixel", "N YIY"),
    ("Width/String", "", "Y NT"),
    ("Width_Offset", " pixel", "N YIY"),
    ("Width_Offset/String", "", "N NT"),
    ("Width_Original", " pixel", "N YIY"),
    ("Width_Original/String", "", "Y NT"),
    ("Width_CleanAperture", " pixel", "N YIY"),
    ("Width_CleanAperture/String", "", "Y NT"),
    ("Height", " pixel", "N YIY"),
    ("Height/String", "", "Y NT"),
    ("Height_Offset", " pixel", "N YIY"),
    ("Height_Offset/String", "", "N NT"),
    ("Height_Original", " pixel", "N YIY"),
    ("Height_Original/String", "", "Y NT"),
    ("Height_CleanAperture", " pixel", "N YI"),
    ("Height_CleanAperture/String", "", "Y NT"),
    ("Stored_Width", "", "N YIY"),
    ("Stored_Height", "", "N YIY"),
    ("Sampled_Width", "", "N YIY"),
    ("Sampled_Height", "", "N YIY"),
    ("PixelAspectRatio", "", "N YFY"),
    ("PixelAspectRatio/String", "", "N NT"),
    ("PixelAspectRatio_Original", "", "N YFY"),
    ("PixelAspectRatio_Original/String", "", "N NT"),
    ("PixelAspectRatio_CleanAperture", "", "N YF"),
    ("PixelAspectRatio_CleanAperture/String", "", "N NT"),
    ("DisplayAspectRatio", "", "N YFY"),
    ("DisplayAspectRatio/String", "", "Y NT"),
    ("DisplayAspectRatio_Original", "", "N YFY"),
    ("DisplayAspectRatio_Original/String", "", "Y NT"),
    ("DisplayAspectRatio_CleanAperture", "", "N YF"),
    ("DisplayAspectRatio_CleanAperture/String", "", "Y NT"),
    ("ActiveFormatDescription", "", "N YNY"),
    ("ActiveFormatDescription/String", "", "Y NT"),
    ("ActiveFormatDescription_MuxingMode", "", "N YT"),
    ("Rotation", "", "N YTY"),
    ("Rotation/String", "", "Y NT"),
    ("FrameRate_Mode", "", "N YTY"),
    ("FrameRate_Mode/String", "", "Y NT"),
    ("FrameRate_Mode_Original", "", "N YTY"),
    ("FrameRate_Mode_Original/String", "", "Y NT"),
    ("FrameRate", " fps", "N YFY"),
    ("FrameRate/String", "", "Y NT"),
    ("FrameRate_Num", "", "N NFN"),
    ("FrameRate_Den", "", "N NFN"),
    ("FrameRate_Minimum", " fps", "N YFY"),
    ("FrameRate_Minimum/String", "", "Y NT"),
    ("FrameRate_Nominal", " fps", "N YFY"),
    ("FrameRate_Nominal/String", "", "Y NT"),
    ("FrameRate_Maximum", " fps", "N YFY"),
    ("FrameRate_Maximum/String", "", "Y NT"),
    ("FrameRate_Original", " fps", "N YFY"),
    ("FrameRate_Original/String", "", "Y NT"),
    ("FrameRate_Original_Num", "", "N NFN"),
    ("FrameRate_Original_Den", "", "N NFN"),
    ("FrameCount", "", "N NIY"),
    ("Source_FrameCount", "", "N NI"),
    ("Standard", "", "Y NTY"),
    ("Resolution", " bit", "N NI"),
    ("Resolution/String", "", "N NT"),
    ("Colorimetry", "", "N NT"),
    ("ColorSpace", "", "Y YTY"),
    ("ChromaSubsampling", "", "N YTY"),
    ("ChromaSubsampling/String", "", "Y NT"),
    ("ChromaSubsampling_Position", "", "N YTY"),
    ("BitDepth", " bit", "N YIY"),
    ("BitDepth/String", "", "Y NT"),
    ("ScanType", "", "N YTY"),
    ("ScanType/String", "", "Y NT"),
    ("ScanType_Original", "", "N YTY"),
    ("ScanType_Original/String", "", "Y NT"),
    ("ScanType_StoreMethod", "", "N YT"),
    ("ScanType_StoreMethod_FieldsPerBlock", "", "N YT"),
    ("ScanType_StoreMethod/String", "", "Y NT"),
    ("ScanOrder", "", "N YTY"),
    ("ScanOrder/String", "", "Y NT"),
    ("ScanOrder_Stored", "", "N YTY"),
    ("ScanOrder_Stored/String", "", "Y NT"),
    ("ScanOrder_StoredDisplayedInverted", "", "N NT"),
    ("ScanOrder_Original", "", "N YTY"),
    ("ScanOrder_Original/String", "", "Y NT"),
    ("Interlacement", "", "N NT"),
    ("Interlacement/String", "", "N NT"),
    ("Compression_Mode", "", "N YTY"),
    ("Compression_Mode/String", "", "Y NT"),
    ("Compression_Ratio", "", "Y YFY"),
    ("Bits-(Pixel*Frame)", "", "Y NFN"),
    ("Delay", " ms", "N NFY"),
    ("Delay/String", "", "N NT"),
    ("Delay/String1", "", "N NT"),
    ("Delay/String2", "", "N NT"),
    ("Delay/String3", "", "N NT"),
    ("Delay/String4", "", "N NT"),
    ("Delay/String5", "", "N NT"),
    ("Delay_Settings", "", "N NT"),
    ("Delay_DropFrame", "", "N NT"),
    ("Delay_Source", "", "N NT"),
    ("Delay_Source/String", "", "N NT"),
    ("Delay_Original", " ms", "N NIY"),
    ("Delay_Original/String", "", "N NT"),
    ("Delay_Original/String1", "", "N NT"),
    ("Delay_Original/String2", "", "N NT"),
    ("Delay_Original/String3", "", "N NT"),
    ("Delay_Original/String4", "", "N NT"),
    ("Delay_Original/String5", "", "N NT"),
    ("Delay_Original_Settings", "", "N NT"),
    ("Delay_Original_DropFrame", "", "N NT"),
    ("Delay_Original_Source", "", "N NT"),
    ("TimeStamp_FirstFrame", " ms", "N YFY"),
    ("TimeStamp_FirstFrame/String", "", "Y NT"),
    ("TimeStamp_FirstFrame/String1", "", "N NT"),
    ("TimeStamp_FirstFrame/String2", "", "N NT"),
    ("TimeStamp_FirstFrame/String3", "", "N NT"),
    ("TimeStamp_FirstFrame/String4", "", "N NT"),
    ("TimeStamp_FirstFrame/String5", "", "N NT"),
    ("TimeCode_FirstFrame", "", "Y YCY"),
    ("TimeCode_Settings", "", "Y YTY"),
    ("TimeCode_Source", "", "Y YTY"),
    ("Gop_OpenClosed", " ", "N YTY"),
    ("Gop_OpenClosed/String", "", "Y NT"),
    ("Gop_OpenClosed_FirstFrame", " ", "N YTY"),
    ("Gop_OpenClosed_FirstFrame/String", "", "Y NT"),
    ("StreamSize", " byte", "N YIY"),
    ("StreamSize/String", "", "Y NT"),
    ("StreamSize/String1", "", "N NT"),
    ("StreamSize/String2", "", "N NT"),
    ("StreamSize/String3", "", "N NT"),
    ("StreamSize/String4", "", "N NT"),
    ("StreamSize/String5", "", "N NT"),
    ("StreamSize_Proportion", "", "N NT"),
    ("StreamSize_Demuxed", " byte", "N YIN"),
    ("StreamSize_Demuxed/String", "", "N NT"),
    ("StreamSize_Demuxed/String1", "", "N NT"),
    ("StreamSize_Demuxed/String2", "", "N NT"),
    ("StreamSize_Demuxed/String3", "", "N NT"),
    ("StreamSize_Demuxed/String4", "", "N NT"),
    ("StreamSize_Demuxed/String5", "", "N NT"),
    ("Source_StreamSize", " byte", "N YIY"),
    ("Source_StreamSize/String", "", "Y NT"),
    ("Source_StreamSize/String1", "", "N NT"),
    ("Source_StreamSize/String2", "", "N NT"),
    ("Source_StreamSize/String3", "", "N NT"),
    ("Source_StreamSize/String4", "", "N NT"),
    ("Source_StreamSize/String5", "", "N NT"),
    ("Source_StreamSize_Proportion", "", "N NT"),
    ("StreamSize_Encoded", " byte", "N YIY"),
    ("StreamSize_Encoded/String", "", "N NT"),
    ("StreamSize_Encoded/String1", "", "N NT"),
    ("StreamSize_Encoded/String2", "", "N NT"),
    ("StreamSize_Encoded/String3", "", "N NT"),
    ("StreamSize_Encoded/String4", "", "N NT"),
    ("StreamSize_Encoded/String5", "", "N NT"),
    ("StreamSize_Encoded_Proportion", "", "N NT"),
    ("Source_StreamSize_Encoded", " byte", "N YIY"),
    ("Source_StreamSize_Encoded/String", "", "N NT"),
    ("Source_StreamSize_Encoded/String1", "", "N NT"),
    ("Source_StreamSize_Encoded/String2", "", "N NT"),
    ("Source_StreamSize_Encoded/String3", "", "N NT"),
    ("Source_StreamSize_Encoded/String4", "", "N NT"),
    ("Source_StreamSize_Encoded/String5", "", "N NT"),
    ("Source_StreamSize_Encoded_Proportion", "", "N NT"),
    ("Alignment", "", "Y NTY"),
    ("Alignment/String", "", "N YT"),
    ("Title", "", "Y YTY"),
    ("Encoded_Application", "", "N YTY"),
    ("Encoded_Application/String", "", "Y NTY"),
    ("Encoded_Application_CompanyName", "", "N YTY"),
    ("Encoded_Application_Name", "", "N YTY"),
    ("Encoded_Application_Version", "", "N YTY"),
    ("Encoded_Application_Url", "", "N YTY"),
    ("Encoded_Library", "", "N YTY"),
    ("Encoded_Library/String", "", "Y NT"),
    ("Encoded_Library_CompanyName", "", "N YTY"),
    ("Encoded_Library_Name", "", "N NTY"),
    ("Encoded_Library_Version", "", "N NTY"),
    ("Encoded_Library_Date", "", "N NTY"),
    ("Encoded_Library_Settings", "", "Y YTY"),
    ("Encoded_OperatingSystem", "", "N YTY"),
    ("Language", "", "N YTY"),
    ("Language/String", "", "Y NT"),
    ("Language/String1", "", "N NT"),
    ("Language/String2", "", "N NT"),
    ("Language/String3", "", "N NT"),
    ("Language/String4", "", "N NT"),
    ("Language_More", "", "Y YTY"),
    ("ServiceKind", "", "N YTY"),
    ("ServiceKind/String", "", "Y NT"),
    ("Disabled", "Yes", "N YTY"),
    ("Disabled/String", "", "Y NT"),
    ("Default", "Yes", "N YTY"),
    ("Default/String", "", "Y NT"),
    ("Forced", "Yes", "N YTY"),
    ("Forced/String", "", "Y NT"),
    ("AlternateGroup", "Yes", "N YTY"),
    ("AlternateGroup/String", "", "Y NT"),
    ("Encoded_Date", "", "Y YTY"),
    ("Tagged_Date", "", "Y YTY"),
    ("Encryption", "", "Y YTY"),
    ("BufferSize", "", "N YTY"),
    ("colour_description_present", "", "N YTY"),
    ("colour_description_present_Source", "", "N YTY"),
    ("colour_description_present_Original", "", "N YTY"),
    ("colour_description_present_Original_Source", "", "N YTY"),
    ("colour_range", "", "Y YTY"),
    ("colour_range_Source", "", "N YTY"),
    ("colour_range_Original", "", "Y YTY"),
    ("colour_range_Original_Source", "", "N YTY"),
    ("colour_primaries", "", "Y YTY"),
    ("colour_primaries_Source", "", "N YTY"),
    ("colour_primaries_Original", "", "Y YTY"),
    ("colour_primaries_Original_Source", "", "N YTY"),
    ("transfer_characteristics", "", "Y YTY"),
    ("transfer_characteristics_Source", "", "N YTY"),
    ("transfer_characteristics_Original", "", "Y YTY"),
    ("transfer_characteristics_Original_Source", "", "N YTY"),
    ("matrix_coefficients", "", "Y YTY"),
    ("matrix_coefficients_Source", "", "N YTY"),
    ("matrix_coefficients_Original", "", "Y YTY"),
    ("matrix_coefficients_Original_Source", "", "N YTY"),
    ("MasteringDisplay_ColorPrimaries", "", "Y YTY"),
    ("MasteringDisplay_ColorPrimaries_Source", "", "N YTY"),
    ("MasteringDisplay_ColorPrimaries_Original", "", "Y YTY"),
    ("MasteringDisplay_ColorPrimaries_Original_Source", "", "N YTY"),
    ("MasteringDisplay_Luminance", "", "Y YTY"),
    ("MasteringDisplay_Luminance_Source", "", "N YTY"),
    ("MasteringDisplay_Luminance_Original", "", "Y YTY"),
    ("MasteringDisplay_Luminance_Original_Source", "", "N YTY"),
    ("MaxCLL", "", "Y YTY"),
    ("MaxCLL_Source", "", "N YTY"),
    ("MaxCLL_Original", "", "Y YTY"),
    ("MaxCLL_Original_Source", "", "N YTY"),
    ("MaxFALL", "", "Y YTY"),
    ("MaxFALL_Source", "", "N YTY"),
    ("MaxFALL_Original", "", "Y YTY"),
    ("MaxFALL_Original_Source", "", "N YTY"),
];

pub static AUDIO: &[(&str, &str, &str)] = &[
    ("Count", "", "N NI"),
    ("Status", "", "N NI"),
    ("StreamCount", "", "N NI"),
    ("StreamKind", "", "N NT"),
    ("StreamKind/String", "", "N NT"),
    ("StreamKindID", "", "N NI"),
    ("StreamKindPos", "", "N NI"),
    ("StreamOrder", "", "N YIY"),
    ("FirstPacketOrder", "", "N YIY"),
    ("Inform", "", "N NT"),
    ("ID", "", "N YTY"),
    ("ID/String", "", "Y NT"),
    ("OriginalSourceMedium_ID", "", "N YTY"),
    ("OriginalSourceMedium_ID/String", "", "Y NT"),
    ("UniqueID", "", "N YTY"),
    ("UniqueID/String", "", "Y NT"),
    ("MenuID", "", "N YTY"),
    ("MenuID/String", "", "Y NT"),
    ("Format", "", "N YTY"),
    ("Format/String", "", "Y NT"),
    ("Format/Info", "", "Y NT"),
    ("Format/Url", "", "N NT"),
    ("Format_Commercial", "", "N YT"),
    ("Format_Commercial_IfAny", "", "Y YTY"),
    ("Format_Version", "", "Y YTY"),
    ("Format_Profile", "", "Y YTY"),
    ("Format_Level", "", "Y YTY"),
    ("Format_Compression", "", "Y YTY"),
    ("Format_Settings", "", "Y NT"),
    ("Format_Settings_SBR", "Yes", "N YTY"),
    ("Format_Settings_SBR/String", "", "N NT"),
    ("Format_Settings_PS", "Yes", "N YTY"),
    ("Format_Settings_PS/String", "", "N NT"),
    ("Format_Settings_Mode", "", "N YTY"),
    ("Format_Settings_ModeExtension", "", "N YTY"),
    ("Format_Settings_Emphasis", "", "N YTY"),
    ("Format_Settings_Floor", "", "Y YTY"),
    ("Format_Settings_Firm", "", "N YTY"),
    ("Format_Settings_Endianness", "", "N YTY"),
    ("Format_Settings_Sign", "", "N YTY"),
    ("Format_Settings_Law", "", "Y YTY"),
    ("Format_Settings_ITU", "", "N YTY"),
    ("Format_Settings_Wrapping", "", "Y YTY"),
    ("Format_AdditionalFeatures", "", "N YTY"),
    ("Matrix_Format", "", "Y YTY"),
    ("InternetMediaType", "", "N YT"),
    ("MuxingMode", "", "Y YTY"),
    ("MuxingMode_MoreInfo", "", "Y NT"),
    ("CodecID", "", "Y YTY"),
    ("CodecID/String", "", "Y NT"),
    ("CodecID/Info", "", "Y NT"),
    ("CodecID/Hint", "", "Y NT"),
    ("CodecID/Url", "", "N NT"),
    ("CodecID_Description", "", "Y YT"),
    ("Codec", "", "N NT"),
    ("Codec/String", "", "N NT"),
    ("Codec/Family", "", "N NT"),
    ("Codec/Info", "", "N NT"),
    ("Codec/Url", "", "N NT"),
    ("Codec/CC", "", "N NT"),
    ("Codec_Description", "", "N NT"),
    ("Codec_Profile", "", "N NT"),
    ("Codec_Settings", "", "N NT"),
    ("Codec_Settings_Automatic", "", "N NT"),
    ("Codec_Settings_Floor", "", "N NT"),
    ("Codec_Settings_Firm", "", "N NT"),
    ("Codec_Settings_Endianness", "", "N NT"),
    ("Codec_Settings_Sign", "", "N NT"),
    ("Codec_Settings_Law", "", "N NT"),
    ("Codec_Settings_ITU", "", "N NT"),
    ("Duration", " ms", "N YFY"),
    ("Duration/String", "", "Y NT"),
    ("Duration/String1", "", "N NT"),
    ("Duration/String2", "", "N NT"),
    ("Duration/String3", "", "N NT"),
    ("Duration/String4", "", "N NT"),
    ("Duration/String5", "", "N NT"),
    ("Duration_FirstFrame", " ms", "N YFY"),
    ("Duration_FirstFrame/String", "", "Y NT"),
    ("Duration_FirstFrame/String1", "", "N NT"),
    ("Duration_FirstFrame/String2", "", "N NT"),
    ("Duration_FirstFrame/String3", "", "N NT"),
    ("Duration_FirstFrame/String4", "", "N NT"),
    ("Duration_FirstFrame/String5", "", "N NT"),
    ("Duration_LastFrame", " ms", "N YFY"),
    ("Duration_LastFrame/String", "", "Y NT"),
    ("Duration_LastFrame/String1", "", "N NT"),
    ("Duration_LastFrame/String2", "", "N NT"),
    ("Duration_LastFrame/String3", "", "N NT"),
    ("Duration_LastFrame/String4", "", "N NT"),
    ("Duration_LastFrame/String5", "", "N NT"),
    ("Source_Duration", " ms", "N YFY"),
    ("Source_Duration/String", "", "Y NT"),
    ("Source_Duration/String1", "", "N NT"),
    ("Source_Duration/String2", "", "N NT"),
    ("Source_Duration/String3", "", "N NT"),
    ("Source_Duration/String4", "", "N NT"),
    ("Source_Duration/String5", "", "N NT"),
    ("Source_Duration_FirstFrame", " ms", "N YFY"),
    ("Source_Duration_FirstFrame/String", "", "Y NT"),
    ("Source_Duration_FirstFrame/String1", "", "N NT"),
    ("Source_Duration_FirstFrame/String2", "", "N NT"),
    ("Source_Duration_FirstFrame/String3", "", "N NT"),
    ("Source_Duration_FirstFrame/String4", "", "N NT"),
    ("Source_Duration_FirstFrame/String5", "", "N NT"),
    ("Source_Duration_LastFrame", " ms", "N YFY"),
    ("Source_Duration_LastFrame/String", "", "Y NT"),
    ("Source_Duration_LastFrame/String1", "", "N NT"),
    ("Source_Duration_LastFrame/String2", "", "N NT"),
    ("Source_Duration_LastFrame/String3", "", "N NT"),
    ("Source_Duration_LastFrame/String4", "", "N NT"),
    ("Source_Duration_LastFrame/String5", "", "N NT"),
    ("BitRate_Mode", "", "N YTY"),
    ("BitRate_Mode/String", "", "Y NT"),
    ("BitRate", " bps", "N YFY"),
    ("BitRate/String", "", "Y NT"),
    ("BitRate_Minimum", " bps", "N YFY"),
    ("BitRate_Minimum/String", "", "Y NT"),
    ("BitRate_Nominal", " bps", "N YFY"),
    ("BitRate_Nominal/String", "", "Y NT"),
    ("BitRate_Maximum", " bps", "N YFY"),
    ("BitRate_Maximum/String", "", "Y NT"),
    ("BitRate_Encoded", " bps", "N YFY"),
    ("BitRate_Encoded/String", "", "N NT"),
    ("Channel(s)", " channel", "N YIY"),
    ("Channel(s)/String", "", "Y NT"),
    ("Channel(s)_Original", " channel", "N YIY"),
    ("Channel(s)_Original/String", "", "Y NT"),
    ("Matrix_Channel(s)", " channel", "N YIY"),
    ("Matrix_Channel(s)/String", "", "Y NT"),
    ("ChannelPositions", "", "N YTY"),
    ("ChannelPositions_Original", "", "N YTY"),
    ("ChannelPositions/String2", "", "N NT"),
    ("ChannelPositions_Original/String2", "", "N NT"),
    ("Matrix_ChannelPositions", "", "Y YTY"),
    ("Matrix_ChannelPositions/String2", "", "N NT"),
    ("ChannelLayout", "", "Y YTY"),
    ("ChannelLayout_Original", "", "Y YTY"),
    ("ChannelLayoutID", "", "N YT"),
    ("SamplesPerFrame", "", "N YFY"),
    ("SamplingRate", " Hz", "N YFY"),
    ("SamplingRate/String", "", "Y NT"),
    ("SamplingCount", "", "N NIY"),
    ("Source_SamplingCount", "", "N NIY"),
    ("FrameRate", " fps", "N YFY"),
    ("FrameRate/String", "", "Y NT"),
    ("FrameRate_Num", "", "N NFN"),
    ("FrameRate_Den", "", "N NFN"),
    ("FrameCount", "", "N NIY"),
    ("Source_FrameCount", "", "N NIY"),
    ("Resolution", " bit", "N NI"),
    ("Resolution/String", "", "N NT"),
    ("BitDepth", " bit", "N YIY"),
    ("BitDepth/String", "", "Y NT"),
    ("BitDepth_Detected", " bit", "N YIY"),
    ("BitDepth_Detected/String", "", "Y NT"),
    ("BitDepth_Stored", " bit", "N YIY"),
    ("BitDepth_Stored/String", "", "Y NT"),
    ("Compression_Mode", "", "N YTY"),
    ("Compression_Mode/String", "", "Y NT"),
    ("Compression_Ratio", "", "Y YF"),
    ("Delay", " ms", "N NFY"),
    ("Delay/String", "", "N NT"),
    ("Delay/String1", "", "N NT"),
    ("Delay/String2", "", "N NT"),
    ("Delay/String3", "", "N NT"),
    ("Delay/String4", "", "N NT"),
    ("Delay/String5", "", "N NT"),
    ("Delay_Settings", "", "N NTY"),
    ("Delay_DropFrame", "", "N NTY"),
    ("Delay_Source", "", "N NTY"),
    ("Delay_Source/String", "", "N NT"),
    ("Delay_Original", " ms", "N NIY"),
    ("Delay_Original/String", "", "N NT"),
    ("Delay_Original/String1", "", "N NT"),
    ("Delay_Original/String2", "", "N NT"),
    ("Delay_Original/String3", "", "N NT"),
    ("Delay_Original/String4", "", "N NT"),
    ("Delay_Original/String5", "", "N NT"),
    ("Delay_Original_Settings", "", "N NT"),
    ("Delay_Original_DropFrame", "", "N NTY"),
    ("Delay_Original_Source", "", "N NTY"),
    ("Video_Delay", " ms", "N NI"),
    ("Video_Delay/String", "", "Y NT"),
    ("Video_Delay/String1", "", "N NT"),
    ("Video_Delay/String2", "", "N NT"),
    ("Video_Delay/String3", "", "N NT"),
    ("Video_Delay/String4", "", "N NT"),
    ("Video_Delay/String5", "", "N NT"),
    ("Video0_Delay", " ms", "N NI"),
    ("Video0_Delay/String", "", "N NT"),
    ("Video0_Delay/String1", "", "N NT"),
    ("Video0_Delay/String2", "", "N NT"),
    ("Video0_Delay/String3", "", "N NT"),
    ("Video0_Delay/String4", "", "N NT"),
    ("Video0_Delay/String5", "", "N NT"),
    ("ReplayGain_Gain", " dB", "N YTY"),
    ("ReplayGain_Gain/String", "", "Y YT"),
    ("ReplayGain_Peak", "", "Y YTY"),
    ("StreamSize", " byte", "N YIY"),
    ("StreamSize/String", "", "Y NT"),
    ("StreamSize/String1", "", "N NT"),
    ("StreamSize/String2", "", "N NT"),
    ("StreamSize/String3", "", "N NT"),
    ("StreamSize/String4", "", "N NT"),
    ("StreamSize/String5", "", "N NT"),
    ("StreamSize_Proportion", "", "N NTY"),
    ("StreamSize_Demuxed", " byte", "N YIN"),
    ("StreamSize_Demuxed/String", "", "N NT"),
    ("StreamSize_Demuxed/String1", "", "N NT"),
    ("StreamSize_Demuxed/String2", "", "N NT"),
    ("StreamSize_Demuxed/String3", "", "N NT"),
    ("StreamSize_Demuxed/String4", "", "N NT"),
    ("StreamSize_Demuxed/String5", "", "N NT"),
    ("Source_StreamSize", " byte", "N YIY"),
    ("Source_StreamSize/String", "", "Y NT"),
    ("Source_StreamSize/String1", "", "N NT"),
    ("Source_StreamSize/String2", "", "N NT"),
    ("Source_StreamSize/String3", "", "N NT"),
    ("Source_StreamSize/String4", "", "N NT"),
    ("Source_StreamSize/String5", "", "N NT"),
    ("Source_StreamSize_Proportion", "", "N NTY"),
    ("StreamSize_Encoded", " byte", "N YIY"),
    ("StreamSize_Encoded/String", "", "N NT"),
    ("StreamSize_Encoded/String1", "", "N NT"),
    ("StreamSize_Encoded/String2", "", "N NT"),
    ("StreamSize_Encoded/String3", "", "N NT"),
    ("StreamSize_Encoded/String4", "", "N NT"),
    ("StreamSize_Encoded/String5", "", "N NT"),
    ("StreamSize_Encoded_Proportion", "", "N NT"),
    ("Source_StreamSize_Encoded", " byte", "N YIY"),
    ("Source_StreamSize_Encoded/String", "", "N NT"),
    ("Source_StreamSize_Encoded/String1", "", "N NT"),
    ("Source_StreamSize_Encoded/String2", "", "N NT"),
    ("Source_StreamSize_Encoded/String3", "", "N NT"),
    ("Source_StreamSize_Encoded/String4", "", "N NT"),
    ("Source_StreamSize_Encoded/String5", "", "N NT"),
    ("Source_StreamSize_Encoded_Proportion", "", "N NT"),
    ("Alignment", "", "N YTY"),
    ("Alignment/String", "", "Y NT"),
    ("Interleave_VideoFrames", "", "N YFY"),
    ("Interleave_Duration", " ms", "N YFY"),
    ("Interleave_Duration/String", "", "Y NT"),
    ("Interleave_Preload", " ms", "N YFY"),
    ("Interleave_Preload/String", "", "Y NT"),
    ("Title", "", "Y YTY"),
    ("Encoded_Application", "", "N YTY"),
    ("Encoded_Application/String", "", "Y NT"),
    ("Encoded_Application_CompanyName", "", "N YTY"),
    ("Encoded_Application_Name", "", "N YTY"),
    ("Encoded_Application_Version", "", "N YTY"),
    ("Encoded_Application_Url", "", "N YT"),
    ("Encoded_Library", "", "N YTY"),
    ("Encoded_Library/String", "", "Y NT"),
    ("Encoded_Library_CompanyName", "", "N YTY"),
    ("Encoded_Library_Name", "", "N NTY"),
    ("Encoded_Library_Version", "", "N NTY"),
    ("Encoded_Library_Date", "", "N NTY"),
    ("Encoded_Library_Settings", "", "Y YTY"),
    ("Encoded_OperatingSystem", "", "N YTY"),
    ("Language", "", "N YTY"),
    ("Language/String", "", "Y NT"),
    ("Language/String1", "", "N NT"),
    ("Language/String2", "", "N NT"),
    ("Language/String3", "", "N NT"),
    ("Language/String4", "", "N NT"),
    ("Language_More", "", "Y YTY"),
    ("ServiceKind", "", "N YTY"),
    ("ServiceKind/String", "", "Y NT"),
    ("Disabled", "Yes", "N YTY"),
    ("Disabled/String", "", "Y NT"),
    ("Default", "Yes", "N YTY"),
    ("Default/String", "", "Y NT"),
    ("Forced", "Yes", "N YTY"),
    ("Forced/String", "", "Y NT"),
    ("AlternateGroup", "Yes", "N YTY"),
    ("AlternateGroup/String", "", "Y NT"),
    ("Encoded_Date", "", "Y YTY"),
    ("Tagged_Date", "", "Y YTY"),
    ("Encryption", "", "Y YTY"),
];

pub static TEXT: &[(&str, &str, &str)] = &[
    ("Count", "", "N NI"),
    ("Status", "", "N NI"),
    ("StreamCount", "", "N NI"),
    ("StreamKind", "", "N NT"),
    ("StreamKind/String", "", "N NT"),
    ("StreamKindID", "", "N NI"),
    ("StreamKindPos", "", "N NI"),
    ("StreamOrder", "", "N YIY"),
    ("FirstPacketOrder", "", "N YI"),
    ("Inform", "", "N NT"),
    ("ID", "", "N YTY"),
    ("ID/String", "", "Y NT"),
    ("OriginalSourceMedium_ID", "", "N YTY"),
    ("OriginalSourceMedium_ID/String", "", "Y NT"),
    ("UniqueID", "", "N YTY"),
    ("UniqueID/String", "", "Y NT"),
    ("MenuID", "", "N YTY"),
    ("MenuID/String", "", "Y NT"),
    ("Format", "", "N YTY"),
    ("Format/String", "", "Y NT"),
    ("Format/Info", "", "Y NT"),
    ("Format/Url", "", "N NT"),
    ("Format_Commercial", "", "N NT"),
    ("Format_Commercial_IfAny", "", "Y YTY"),
    ("Format_Version", "", "Y NTY"),
    ("Format_Profile", "", "Y NTY"),
    ("Format_Compression", "", "Y NTY"),
    ("Format_Settings", "", "Y NTY"),
    ("Format_Settings_Wrapping", "", "Y YTY"),
    ("Format_AdditionalFeatures", "", "N YTY"),
    ("InternetMediaType", "", "N YT"),
    ("MuxingMode", "", "Y YTY"),
    ("MuxingMode_MoreInfo", "", "Y NTY"),
    ("CodecID", "", "Y YTY"),
    ("CodecID/String", "", "Y NT"),
    ("CodecID/Info", "", "Y NT"),
    ("CodecID/Hint", "", "Y NT"),
    ("CodecID/Url", "", "N NT"),
    ("CodecID_Description", "", "Y YT"),
    ("Codec", "", "N YT"),
    ("Codec/String", "", "N NT"),
    ("Codec/Info", "", "N NT"),
    ("Codec/Url", "", "N NT"),
    ("Codec/CC", "", "N NT"),
    ("Duration", " ms", "N YFY"),
    ("Duration/String", "", "Y NT"),
    ("Duration/String1", "", "N NT"),
    ("Duration/String2", "", "N NT"),
    ("Duration/String3", "", "N NT"),
    ("Duration/String4", "", "N NT"),
    ("Duration/String5", "", "N NT"),
    ("Duration_FirstFrame", " ms", "N YFY"),
    ("Duration_FirstFrame/String", "", "Y NT"),
    ("Duration_FirstFrame/String1", "", "N NT"),
    ("Duration_FirstFrame/String2", "", "N NT"),
    ("Duration_FirstFrame/String3", "", "N NT"),
    ("Duration_FirstFrame/String4", "", "N NT"),
    ("Duration_FirstFrame/String5", "", "N NT"),
    ("Duration_LastFrame", " ms", "N YFY"),
    ("Duration_LastFrame/String", "", "Y NT"),
    ("Duration_LastFrame/String1", "", "N NT"),
    ("Duration_LastFrame/String2", "", "N NT"),
    ("Duration_LastFrame/String3", "", "N NT"),
    ("Duration_LastFrame/String4", "", "N NT"),
    ("Duration_LastFrame/String5", "", "N NT"),
    ("Source_Duration", " ms", "N YFY"),
    ("Source_Duration/String", "", "Y NT"),
    ("Source_Duration/String1", "", "N NT"),
    ("Source_Duration/String2", "", "N NT"),
    ("Source_Duration/String3", "", "N NT"),
    ("Source_Duration/String4", "", "N NT"),
    ("Source_Duration/String5", "", "N NT"),
    ("Source_Duration_FirstFrame", " ms", "N YFY"),
    ("Source_Duration_FirstFrame/String", "", "Y NT"),
    ("Source_Duration_FirstFrame/String1", "", "N NT"),
    ("Source_Duration_FirstFrame/String2", "", "N NT"),
    ("Source_Duration_FirstFrame/String3", "", "N NT"),
    ("Source_Duration_FirstFrame/String4", "", "N NT"),
    ("Source_Duration_FirstFrame/String5", "", "N NT"),
    ("Source_Duration_LastFrame", " ms", "N YFY"),
    ("Source_Duration_LastFrame/String", "", "Y NT"),
    ("Source_Duration_LastFrame/String1", "", "N NT"),
    ("Source_Duration_LastFrame/String2", "", "N NT"),
    ("Source_Duration_LastFrame/String3", "", "N NT"),
    ("Source_Duration_LastFrame/String4", "", "N NT"),
    ("Source_Duration_LastFrame/String5", "", "N NT"),
    ("BitRate_Mode", "", "N YTY"),
    ("BitRate_Mode/String", "", "Y NT"),
    ("BitRate", " bps", "N YFY"),
    ("BitRate/String", "", "Y NT"),
    ("BitRate_Minimum", " bps", "N YFY"),
    ("BitRate_Minimum/String", "", "Y NT"),
    ("BitRate_Nominal", " bps", "N YFY"),
    ("BitRate_Nominal/String", "", "Y NT"),
    ("BitRate_Maximum", " bps", "N YFY"),
    ("BitRate_Maximum/String", "", "Y NT"),
    ("BitRate_Encoded", " bps", "N YFY"),
    ("BitRate_Encoded/String", "", "N NT"),
    ("Width", " character", "N YIY"),
    ("Width/String", "", "Y NT"),
    ("Height", " character", "N YIY"),
    ("Height/String", "", "Y NT"),
    ("FrameRate_Mode", "", "N YTY"),
    ("FrameRate_Mode/String", "", "N NT"),
    ("FrameRate", " fps", "N YFY"),
    ("FrameRate/String", "", "N NT"),
    ("FrameRate_Num", "", "N NFN"),
    ("FrameRate_Den", "", "N NFN"),
    ("FrameRate_Minimum", " fps", "N YFY"),
    ("FrameRate_Minimum/String", "", "N NT"),
    ("FrameRate_Nominal", " fps", "N YFY"),
    ("FrameRate_Nominal/String", "", "N NT"),
    ("FrameRate_Maximum", " fps", "N YFY"),
    ("FrameRate_Maximum/String", "", "N NT"),
    ("FrameRate_Original", " fps", "N YFY"),
    ("FrameRate_Original/String", "", "N NT"),
    ("FrameCount", "", "N NIY"),
    ("ElementCount", "", "Y NIY"),
    ("Source_FrameCount", "", "N NIY"),
    ("ColorSpace", "", "Y YTY"),
    ("ChromaSubsampling", "", "Y YTY"),
    ("Resolution", " bit", "N NI"),
    ("Resolution/String", "", "N NT"),
    ("BitDepth", " bit", "N YIY"),
    ("BitDepth/String", "", "Y NT"),
    ("Compression_Mode", "", "N YTY"),
    ("Compression_Mode/String", "", "Y NT"),
    ("Compression_Ratio", "", "Y YF"),
    ("Delay", " ms", "N NFY"),
    ("Delay/String", "", "N NT"),
    ("Delay/String1", "", "N NT"),
    ("Delay/String2", "", "N NT"),
    ("Delay/String3", "", "N NT"),
    ("Delay/String4", "", "N NT"),
    ("Delay/String5", "", "N NT"),
    ("Delay_Settings", "", "N NT"),
    ("Delay_DropFrame", "", "N NTY"),
    ("Delay_Source", "", "N NTY"),
    ("Delay_Source/String", "", "N NT"),
    ("Delay_Original", " ms", "N NIY"),
    ("Delay_Original/String", "", "N NT"),
    ("Delay_Original/String1", "", "N NT"),
    ("Delay_Original/String2", "", "N NT"),
    ("Delay_Original/String3", "", "N NT"),
    ("Delay_Original/String4", "", "N NT"),
    ("Delay_Original/String5", "", "N NT"),
    ("Delay_Original_Settings", "", "N NT"),
    ("Delay_Original_DropFrame", "", "N NT"),
    ("Delay_Original_Source", "", "N NTY"),
    ("Video_Delay", " ms", "N NI"),
    ("Video_Delay/String", "", "Y NT"),
    ("Video_Delay/String1", "", "N NT"),
    ("Video_Delay/String2", "", "N NT"),
    ("Video_Delay/String3", "", "N NT"),
    ("Video_Delay/String4", "", "N NT"),
    ("Video_Delay/String5", "", "N NT"),
    ("Video0_Delay", " ms", "N NI"),
    ("Video0_Delay/String", "", "N NT"),
    ("Video0_Delay/String1", "", "N NT"),
    ("Video0_Delay/String2", "", "N NT"),
    ("Video0_Delay/String3", "", "N NT"),
    ("Video0_Delay/String4", "", "N NT"),
    ("Video0_Delay/String5", "", "N NT"),
    ("StreamSize", " byte", "N YIY"),
    ("StreamSize/String", "", "Y NT"),
    ("StreamSize/String1", "", "N NT"),
    ("StreamSize/String2", "", "N NT"),
    ("StreamSize/String3", "", "N NT"),
    ("StreamSize/String4", "", "N NT"),
    ("StreamSize/String5", "", "N NT"),
    ("StreamSize_Proportion", "", "N NT"),
    ("StreamSize_Demuxed", " byte", "N YIN"),
    ("StreamSize_Demuxed/String", "", "N NT"),
    ("StreamSize_Demuxed/String1", "", "N NT"),
    ("StreamSize_Demuxed/String2", "", "N NT"),
    ("StreamSize_Demuxed/String3", "", "N NT"),
    ("StreamSize_Demuxed/String4", "", "N NT"),
    ("StreamSize_Demuxed/String5", "", "N NT"),
    ("Source_StreamSize", " byte", "N YIY"),
    ("Source_StreamSize/String", "", "Y NT"),
    ("Source_StreamSize/String1", "", "N NT"),
    ("Source_StreamSize/String2", "", "N NT"),
    ("Source_StreamSize/String3", "", "N NT"),
    ("Source_StreamSize/String4", "", "N NT"),
    ("Source_StreamSize/String5", "", "N NT"),
    ("Source_StreamSize_Proportion", "", "N NT"),
    ("StreamSize_Encoded", " byte", "N YIY"),
    ("StreamSize_Encoded/String", "", "N NT"),
    ("StreamSize_Encoded/String1", "", "N NT"),
    ("StreamSize_Encoded/String2", "", "N NT"),
    ("StreamSize_Encoded/String3", "", "N NT"),
    ("StreamSize_Encoded/String4", "", "N NT"),
    ("StreamSize_Encoded/String5", "", "N NT"),
    ("StreamSize_Encoded_Proportion", "", "N NT"),
    ("Source_StreamSize_Encoded", " byte", "N YI"),
    ("Source_StreamSize_Encoded/String", "", "N NT"),
    ("Source_StreamSize_Encoded/String1", "", "N NT"),
    ("Source_StreamSize_Encoded/String2", "", "N NT"),
    ("Source_StreamSize_Encoded/String3", "", "N NT"),
    ("Source_StreamSize_Encoded/String4", "", "N NT"),
    ("Source_StreamSize_Encoded/String5", "", "N NT"),
    ("Source_StreamSize_Encoded_Proportion", "", "N NT"),
    ("Title", "", "Y YTY"),
    ("Encoded_Application", "", "N YT"),
    ("Encoded_Application/String", "", "Y NT"),
    ("Encoded_Application_CompanyName", "", "N YTY"),
    ("Encoded_Application_Name", "", "N YTY"),
    ("Encoded_Application_Version", "", "N YTY"),
    ("Encoded_Application_Url", "", "N YTY"),
    ("Encoded_Library", "", "N YT"),
    ("Encoded_Library/String", "", "Y NT"),
    ("Encoded_Library_CompanyName", "", "N YTY"),
    ("Encoded_Library_Name", "", "N NTY"),
    ("Encoded_Library_Version", "", "N NTY"),
    ("Encoded_Library_Date", "", "N NTY"),
    ("Encoded_Library_Settings", "", "Y YTY"),
    ("Encoded_OperatingSystem", "", "N YTY"),
    ("Language", "", "N YTY"),
    ("Language/String", "", "Y NT"),
    ("Language/String1", "", "N NT"),
    ("Language/String2", "", "N NT"),
    ("Language/String3", "", "N NT"),
    ("Language/String4", "", "N NT"),
    ("Language_More", "", "Y YTY"),
    ("ServiceKind", "", "N YTY"),
    ("ServiceKind/String", "", "Y NT"),
    ("Disabled", "Yes", "N YTY"),
    ("Disabled/String", "", "Y NT"),
    ("Default", "Yes", "N YTY"),
    ("Default/String", "", "Y NT"),
    ("Forced", "Yes", "N YTY"),
    ("Forced/String", "", "Y NT"),
    ("AlternateGroup", "Yes", "N YTY"),
    ("AlternateGroup/String", "", "Y NT"),
    ("Summary", "", "N NTY"),
    ("Encoded_Date", "", "Y YTY"),
    ("Tagged_Date", "", "Y YTY"),
    ("Encryption", "", "Y YTY"),
];

pub static OTHER: &[(&str, &str, &str)] = &[
    ("Count", "", "N NI"),
    ("Status", "", "N NI"),
    ("StreamCount", "", "N NI"),
    ("StreamKind", "", "N NT"),
    ("StreamKind/String", "", "N NT"),
    ("StreamKindID", "", "N NI"),
    ("StreamKindPos", "", "N NI"),
    ("StreamOrder", "", "N YIY"),
    ("FirstPacketOrder", "", "N YIY"),
    ("Inform", "", "N NT"),
    ("ID", "", "N YTY"),
    ("ID/String", "", "Y NT"),
    ("OriginalSourceMedium_ID", "", "N YTY"),
    ("OriginalSourceMedium_ID/String", "", "Y NT"),
    ("UniqueID", "", "N YTY"),
    ("UniqueID/String", "", "Y NT"),
    ("MenuID", "", "N YTY"),
    ("MenuID/String", "", "Y NT"),
    ("Type", "", "Y YTY"),
    ("Format", "", "N YTY"),
    ("Format/String", "", "Y NT"),
    ("Format/Info", "", "N NT"),
    ("Format/Url", "", "N NT"),
    ("Format_Commercial", "", "N NT"),
    ("Format_Commercial_IfAny", "", "Y YTY"),
    ("Format_Version", "", "Y NTY"),
    ("Format_Profile", "", "Y NTY"),
    ("Format_Compression", "", "Y NTY"),
    ("Format_Settings", "", "Y NTY"),
    ("Format_AdditionalFeatures", "", "N YTY"),
    ("MuxingMode", "", "Y YTY"),
    ("CodecID", "", "Y YTY"),
    ("CodecID/String", "", "Y NT"),
    ("CodecID/Info", "", "Y NT"),
    ("CodecID/Hint", "", "Y NT"),
    ("CodecID/Url", "", "N NT"),
    ("CodecID_Description", "", "Y YT"),
    ("Duration", " ms", "N YFY"),
    ("Duration/String", "", "Y NT"),
    ("Duration/String1", "", "N NT"),
    ("Duration/String2", "", "N NT"),
    ("Duration/String3", "", "N NT"),
    ("Duration/String4", "", "N NT"),
    ("Duration/String5", "", "N NT"),
    ("Duration_Start", "", "Y YTY"),
    ("Duration_End", "", "Y YTY"),
    ("Source_Duration", " ms", "N YFY"),
    ("Source_Duration/String", "", "Y NT"),
    ("Source_Duration/String1", "", "N NT"),
    ("Source_Duration/String2", "", "N NT"),
    ("Source_Duration/String3", "", "N NT"),
    ("Source_Duration/String4", "", "N NT"),
    ("Source_Duration/String5", "", "N NT"),
    ("Source_Duration_FirstFrame", " ms", "N YFY"),
    ("Source_Duration_FirstFrame/String", "", "Y NT"),
    ("Source_Duration_FirstFrame/String1", "", "N NT"),
    ("Source_Duration_FirstFrame/String2", "", "N NT"),
    ("Source_Duration_FirstFrame/String3", "", "N NT"),
    ("Source_Duration_FirstFrame/String4", "", "N NT"),
    ("Source_Duration_FirstFrame/String5", "", "N NT"),
    ("Source_Duration_LastFrame", " ms", "N YFY"),
    ("Source_Duration_LastFrame/String", "", "Y NT"),
    ("Source_Duration_LastFrame/String1", "", "N NT"),
    ("Source_Duration_LastFrame/String2", "", "N NT"),
    ("Source_Duration_LastFrame/String3", "", "N NT"),
    ("Source_Duration_LastFrame/String4", "", "N NT"),
    ("Source_Duration_LastFrame/String5", "", "N NT"),
    ("BitRate_Mode", "", "N YTY"),
    ("BitRate_Mode/String", "", "Y NT"),
    ("BitRate", " bps", "N YFY"),
    ("BitRate/String", "", "Y NT"),
    ("BitRate_Minimum", " bps", "N YFY"),
    ("BitRate_Minimum/String", "", "Y NT"),
    ("BitRate_Nominal", " bps", "N YFY"),
    ("BitRate_Nominal/String", "", "Y NT"),
    ("BitRate_Maximum", " bps", "N YFY"),
    ("BitRate_Maximum/String", "", "Y NT"),
    ("BitRate_Encoded", " bps", "N YFY"),
    ("BitRate_Encoded/String", "", "N NT"),
    ("FrameRate", " fps", "N YFY"),
    ("FrameRate/String", "", "Y NT"),
    ("FrameRate_Num", "", "N NFN"),
    ("FrameRate_Den", "", "N NFN"),
    ("FrameCount", "", "N NIY"),
    ("Source_FrameCount", "", "N NI"),
    ("Delay", " ms", "N NFY"),
    ("Delay/String", "", "N NT"),
    ("Delay/String1", "", "N NT"),
    ("Delay/String2", "", "N NT"),
    ("Delay/String3", "", "N NT"),
    ("Delay/String4", "", "N NT"),
    ("Delay/String5", "", "N NT"),
    ("Delay_Settings", "", "N NT"),
    ("Delay_DropFrame", "", "N NT"),
    ("Delay_Source", "", "N NT"),
    ("Delay_Source/String", "", "N NT"),
    ("Delay_Original", " ms", "N NIY"),
    ("Delay_Original/String", "", "N NT"),
    ("Delay_Original/String1", "", "N NT"),
    ("Delay_Original/String2", "", "N NT"),
    ("Delay_Original/String3", "", "N NT"),
    ("Delay_Original/String4", "", "N NT"),
    ("Delay_Original/String5", "", "N NT"),
    ("Delay_Original_Settings", "", "N NT"),
    ("Delay_Original_DropFrame", "", "N NT"),
    ("Delay_Original_Source", "", "N NT"),
    ("Video_Delay", " ms", "N NI"),
    ("Video_Delay/String", "", "Y NT"),
    ("Video_Delay/String1", "", "N NT"),
    ("Video_Delay/String2", "", "N NT"),
    ("Video_Delay/String3", "", "N NT"),
    ("Video_Delay/String4", "", "N NT"),
    ("Video_Delay/String5", "", "N NT"),
    ("Video0_Delay", " ms", "N NI"),
    ("Video0_Delay/String", "", "N NT"),
    ("Video0_Delay/String1", "", "N NT"),
    ("Video0_Delay/String2", "", "N NT"),
    ("Video0_Delay/String3", "", "N NT"),
    ("Video0_Delay/String4", "", "N NT"),
    ("Video0_Delay/String5", "", "N NT"),
    ("TimeStamp_FirstFrame", " ms", "N YFY"),
    ("TimeStamp_FirstFrame/String", "", "Y NT"),
    ("TimeStamp_FirstFrame/String1", "", "N NT"),
    ("TimeStamp_FirstFrame/String2", "", "N NT"),
    ("TimeStamp_FirstFrame/String3", "", "N NT"),
    ("TimeStamp_FirstFrame/String4", "", "N NT"),
    ("TimeStamp_FirstFrame/String5", "", "N NT"),
    ("TimeCode_FirstFrame", "", "Y YCY"),
    ("TimeCode_Settings", "", "Y YTY"),
    ("TimeCode_Striped", "Yes", "N YTY"),
    ("TimeCode_Striped/String", "", "Y NT"),
    ("StreamSize", " byte", "N YIY"),
    ("StreamSize/String", "", "Y NT"),
    ("StreamSize/String1", "", "N NT"),
    ("StreamSize/String2", "", "N NT"),
    ("StreamSize/String3", "", "N NT"),
    ("StreamSize/String4", "", "N NT"),
    ("StreamSize/String5", "", "N NT"),
    ("StreamSize_Proportion", "", "N NT"),
    ("StreamSize_Demuxed", " byte", "N YIN"),
    ("StreamSize_Demuxed/String", "", "N NT"),
    ("StreamSize_Demuxed/String1", "", "N NT"),
    ("StreamSize_Demuxed/String2", "", "N NT"),
    ("StreamSize_Demuxed/String3", "", "N NT"),
    ("StreamSize_Demuxed/String4", "", "N NT"),
    ("StreamSize_Demuxed/String5", "", "N NT"),
    ("Source_StreamSize", " byte", "N YIY"),
    ("Source_StreamSize/String", "", "Y NT"),
    ("Source_StreamSize/String1", "", "N NT"),
    ("Source_StreamSize/String2", "", "N NT"),
    ("Source_StreamSize/String3", "", "N NT"),
    ("Source_StreamSize/String4", "", "N NT"),
    ("Source_StreamSize/String5", "", "N NT"),
    ("Source_StreamSize_Proportion", "", "N NT"),
    ("StreamSize_Encoded", " byte", "N YIY"),
    ("StreamSize_Encoded/String", "", "N NT"),
    ("StreamSize_Encoded/String1", "", "N NT"),
    ("StreamSize_Encoded/String2", "", "N NT"),
    ("StreamSize_Encoded/String3", "", "N NT"),
    ("StreamSize_Encoded/String4", "", "N NT"),
    ("StreamSize_Encoded/String5", "", "N NT"),
    ("StreamSize_Encoded_Proportion", "", "N NT"),
    ("Source_StreamSize_Encoded", " byte", "N YIY"),
    ("Source_StreamSize_Encoded/String", "", "N NT"),
    ("Source_StreamSize_Encoded/String1", "", "N NT"),
    ("Source_StreamSize_Encoded/String2", "", "N NT"),
    ("Source_StreamSize_Encoded/String3", "", "N NT"),
    ("Source_StreamSize_Encoded/String4", "", "N NT"),
    ("Source_StreamSize_Encoded/String5", "", "N NT"),
    ("Source_StreamSize_Encoded_Proportion", "", "N NT"),
    ("Title", "", "Y YTY"),
    ("Language", "", "N YTY"),
    ("Language/String", "", "Y NT"),
    ("Language/String1", "", "N NT"),
    ("Language/String2", "", "N NT"),
    ("Language/String3", "", "N NT"),
    ("Language/String4", "", "N NT"),
    ("Language_More", "", "Y YTY"),
    ("ServiceKind", "", "N YTY"),
    ("ServiceKind/String", "", "Y NT"),
    ("Disabled", "Yes", "N YTY"),
    ("Disabled/String", "", "Y NT"),
    ("Default", "Yes", "N YTY"),
    ("Default/String", "", "Y NT"),
    ("Forced", "Yes", "N YTY"),
    ("Forced/String", "", "Y NT"),
    ("AlternateGroup", "Yes", "N YTY"),
    ("AlternateGroup/String", "", "Y NT"),
];

pub static IMAGE: &[(&str, &str, &str)] = &[
    ("Count", "", "N NI"),
    ("Status", "", "N NI"),
    ("StreamCount", "", "N NI"),
    ("StreamKind", "", "N NT"),
    ("StreamKind/String", "", "N NT"),
    ("StreamKindID", "", "N NI"),
    ("StreamKindPos", "", "N NI"),
    ("StreamOrder", "", "N YIY"),
    ("FirstPacketOrder", "", "N YIY"),
    ("Inform", "", "N NT"),
    ("ID", "", "N YTY"),
    ("ID/String", "", "Y NT"),
    ("OriginalSourceMedium_ID", "", "N YTY"),
    ("OriginalSourceMedium_ID/String", "", "Y NT"),
    ("UniqueID", "", "N YTY"),
    ("UniqueID/String", "", "Y NT"),
    ("MenuID", "", "N YTY"),
    ("MenuID/String", "", "Y NT"),
    ("Title", "", "Y YTY"),
    ("Format", "", "N YTY"),
    ("Format/String", "", "Y NT"),
    ("Format/Info", "", "Y NT"),
    ("Format/Url", "", "N NT"),
    ("Format_Commercial", "", "N NT"),
    ("Format_Commercial_IfAny", "", "Y YTY"),
    ("Format_Version", "", "Y NTY"),
    ("Format_Profile", "", "Y NTY"),
    ("Format_Settings_Endianness", "", "N YTY"),
    ("Format_Settings_Packing", "", "N YTY"),
    ("Format_Compression", "", "Y YTY"),
    ("Format_Settings", "", "Y NT"),
    ("Format_Settings_Wrapping", "", "Y YTY"),
    ("Format_AdditionalFeatures", "", "N YTY"),
    ("InternetMediaType", "", "N YT"),
    ("CodecID", "", "Y YTY"),
    ("CodecID/String", "", "Y NT"),
    ("CodecID/Info", "", "Y NT"),
    ("CodecID/Hint", "", "Y NT"),
    ("CodecID/Url", "", "N NT"),
    ("CodecID_Description", "", "Y YT"),
    ("Codec", "", "N NT"),
    ("Codec/String", "", "N NT"),
    ("Codec/Family", "", "N NT"),
    ("Codec/Info", "", "N NT"),
    ("Codec/Url", "", "N NT"),
    ("Width", " pixel", "N YIY"),
    ("Width/String", "", "Y NT"),
    ("Width_Offset", " pixel", "N YIY"),
    ("Width_Offset/String", "", "N NT"),
    ("Width_Original", " pixel", "N YIY"),
    ("Width_Original/String", "", "Y NT"),
    ("Height", " pixel", "N YIY"),
    ("Height/String", "", "Y NT"),
    ("Height_Offset", " pixel", "N YIY"),
    ("Height_Offset/String", "", "N NT"),
    ("Height_Original", " pixel", "N YIY"),
    ("Height_Original/String", "", "Y NT"),
    ("PixelAspectRatio", "", "N YFY"),
    ("PixelAspectRatio/String", "", "N NT"),
    ("PixelAspectRatio_Original", "", "N YFY"),
    ("PixelAspectRatio_Original/String", "", "N NT"),
    ("DisplayAspectRatio", "", "N YFY"),
    ("DisplayAspectRatio/String", "", "Y NT"),
    ("DisplayAspectRatio_Original", "", "N YFY"),
    ("DisplayAspectRatio_Original/String", "", "Y NT"),
    ("ColorSpace", "", "Y YTY"),
    ("ChromaSubsampling", "", "Y YTY"),
    ("Resolution", " bit", "N NI"),
    ("Resolution/String", "", "N NT"),
    ("BitDepth", " bit", "N YIY"),
    ("BitDepth/String", "", "Y NT"),
    ("Compression_Mode", "", "N YTY"),
    ("Compression_Mode/String", "", "Y NT"),
    ("Compression_Ratio", "", "Y YF"),
    ("StreamSize", " byte", "N YIY"),
    ("StreamSize/String", "", "Y NT"),
    ("StreamSize/String1", "", "N NT"),
    ("StreamSize/String2", "", "N NT"),
    ("StreamSize/String3", "", "N NT"),
    ("StreamSize/String4", "", "N NT"),
    ("StreamSize/String5", "", "N NT"),
    ("StreamSize_Proportion", "", "N NT"),
    ("StreamSize_Demuxed", " byte", "N YIN"),
    ("StreamSize_Demuxed/String", "", "N NT"),
    ("StreamSize_Demuxed/String1", "", "N NT"),
    ("StreamSize_Demuxed/String2", "", "N NT"),
    ("StreamSize_Demuxed/String3", "", "N NT"),
    ("StreamSize_Demuxed/String4", "", "N NT"),
    ("StreamSize_Demuxed/String5", "", "N NT"),
    ("Encoded_Library", "", "N YTY"),
    ("Encoded_Library/String", "", "Y NT"),
    ("Encoded_Library_Name", "", "N NTY"),
    ("Encoded_Library_Version", "", "N NTY"),
    ("Encoded_Library_Date", "", "N NTY"),
    ("Encoded_Library_Settings", "", "Y YTY"),
    ("Language", "", "N YTY"),
    ("Language/String", "", "Y NT"),
    ("Language/String1", "", "N NT"),
    ("Language/String2", "", "N NT"),
    ("Language/String3", "", "N NT"),
    ("Language/String4", "", "N NT"),
    ("Language_More", "", "Y YTY"),
    ("ServiceKind", "", "N YTY"),
    ("ServiceKind/String", "", "Y NT"),
    ("Disabled", "Yes", "N YTY"),
    ("Disabled/String", "", "Y NT"),
    ("Default", "Yes", "N YTY"),
    ("Default/String", "", "Y NT"),
    ("Forced", "Yes", "N YTY"),
    ("Forced/String", "", "Y NT"),
    ("AlternateGroup", "Yes", "N YTY"),
    ("AlternateGroup/String", "", "Y NT"),
    ("Summary", "", "N NTY"),
    ("Encoded_Date", "", "Y YTY"),
    ("Tagged_Date", "", "Y YTY"),
    ("Encryption", "", "Y YTY"),
    ("colour_description_present", "", "N YTY"),
    ("colour_primaries", "", "Y YTY"),
    ("transfer_characteristics", "", "Y YTY"),
    ("matrix_coefficients", "", "Y YTY"),
    ("colour_description_present_Original", "", "N YTY"),
    ("colour_primaries_Original", "", "Y YTY"),
    ("transfer_characteristics_Original", "", "Y YTY"),
    ("matrix_coefficients_Original", "", "Y YTY"),
];

pub static MENU: &[(&str, &str, &str)] = &[
    ("Count", "", "N NI"),
    ("Status", "", "N NI"),
    ("StreamCount", "", "N NI"),
    ("StreamKind", "", "N NT"),
    ("StreamKind/String", "", "N NT"),
    ("StreamKindID", "", "N NI"),
    ("StreamKindPos", "", "N NI"),
    ("StreamOrder", "", "N YIY"),
    ("FirstPacketOrder", "", "N YIY"),
    ("Inform", "", "N NT"),
    ("ID", "", "N YTY"),
    ("ID/String", "", "Y NT"),
    ("OriginalSourceMedium_ID", "", "N YTY"),
    ("OriginalSourceMedium_ID/String", "", "Y NT"),
    ("UniqueID", "", "N YTY"),
    ("UniqueID/String", "", "Y NT"),
    ("MenuID", "", "N YTY"),
    ("MenuID/String", "", "Y NT"),
    ("Format", "", "N YTY"),
    ("Format/String", "", "N NT"),
    ("Format/Info", "", "N NT"),
    ("Format/Url", "", "N NT"),
    ("Format_Commercial", "", "N NT"),
    ("Format_Commercial_IfAny", "", "Y YTY"),
    ("Format_Version", "", "Y NTY"),
    ("Format_Profile", "", "Y NTY"),
    ("Format_Compression", "", "Y NTY"),
    ("Format_Settings", "", "Y NTY"),
    ("Format_AdditionalFeatures", "", "N YTY"),
    ("CodecID", "", "Y YTY"),
    ("CodecID/String", "", "Y NT"),
    ("CodecID/Info", "", "Y NT"),
    ("CodecID/Hint", "", "Y NT"),
    ("CodecID/Url", "", "N NT"),
    ("CodecID_Description", "", "Y YT"),
    ("Codec", "", "N YT"),
    ("Codec/String", "", "N NT"),
    ("Codec/Info", "", "N NT"),
    ("Codec/Url", "", "N NT"),
    ("Duration", " ms", "N YFY"),
    ("Duration/String", "", "Y NT"),
    ("Duration/String1", "", "N NT"),
    ("Duration/String2", "", "N NT"),
    ("Duration/String3", "", "N NT"),
    ("Duration/String4", "", "N NT"),
    ("Duration/String5", "", "N NT"),
    ("Duration_Start", "", "Y YTY"),
    ("Duration_End", "", "Y YTY"),
    ("Delay", " ms", "N NFY"),
    ("Delay/String", "", "N NT"),
    ("Delay/String1", "", "N NT"),
    ("Delay/String2", "", "N NT"),
    ("Delay/String3", "", "N NT"),
    ("Delay/String4", "", "N NT"),
    ("Delay/String5", "", "N NT"),
    ("Delay_Settings", "", "N NT"),
    ("Delay_DropFrame", "", "N NTY"),
    ("Delay_Source", "", "N NTY"),
    ("List_StreamKind", "", "N YTY"),
    ("List_StreamPos", "", "N YTY"),
    ("List", "", "N YT"),
    ("List/String", "", "Y NT"),
    ("Title", "", "Y YTY"),
    ("Language", "", "N YTY"),
    ("Language/String", "", "Y NT"),
    ("Language/String1", "", "N NT"),
    ("Language/String2", "", "N NT"),
    ("Language/String3", "", "N NT"),
    ("Language/String4", "", "N NT"),
    ("Language_More", "", "Y YT"),
    ("ServiceKind", "", "N YTY"),
    ("ServiceKind/String", "", "Y NT"),
    ("ServiceName", "", "Y YTY"),
    ("ServiceChannel", "", "Y YTY"),
    ("Service/Url", "", "Y YT"),
    ("ServiceProvider", "", "Y YTY"),
    ("ServiceProvider/Url", "", "Y YTN"),
    ("ServiceType", "", "Y YTY"),
    ("NetworkName", "", "Y YTY"),
    ("Original/NetworkName", "", "Y YTY"),
    ("Countries", "", "Y YTY"),
    ("TimeZones", "", "Y YTY"),
    ("LawRating", "", "Y YTY"),
    ("LawRating_Reason", "", "Y YTY"),
    ("Disabled", "Yes", "N YTY"),
    ("Disabled/String", "", "Y NT"),
    ("Default", "Yes", "N YTY"),
    ("Default/String", "", "Y NT"),
    ("Forced", "Yes", "N YTY"),
    ("Forced/String", "", "Y NT"),
    ("AlternateGroup", "Yes", "N YTY"),
    ("AlternateGroup/String", "", "Y NT"),
    ("Chapters_Pos_Begin", "", "N NI"),
    ("Chapters_Pos_End", "", "N NI"),
];
